{
  "openapi": "3.0.0",
  "info": {
    "title": "Load Balancer Activations",
    "version": "v2"
  },
  "servers": [
    {
      "url": "https://{hostname}/cloudlets/api/v2"
    }
  ],
  "paths": {
    "/origins/currentActivations": {
      "get": {
        "operationId": "get-origins-currentactivations",
        "summary": "List current load balancing activations",
        "tags": [
          "Load balancing activations"
        ],
        "description": "Run this operation to return information about all the current load balancing activations.\n",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "loadBalancer1": {
                    "PRODUCTION": {
                      "activatedBy": "tyamada",
                      "activatedDate": "2018-01-02T00:00:00.000Z",
                      "network": "PRODUCTION",
                      "originId": "loadBalancer1",
                      "status": "active",
                      "version": 1
                    },
                    "STAGING": {
                      "activatedBy": "adevi",
                      "activatedDate": "2018-01-01T00:00:00.000Z",
                      "network": "PRODUCTION",
                      "originId": "loadBalancer1",
                      "status": "active",
                      "version": 2
                    }
                  },
                  "loadBalancer2": {
                    "STAGING": {
                      "activatedBy": "afero",
                      "activatedDate": "2018-12-31T00:00:00.000Z",
                      "network": "STAGING",
                      "originId": "loadBalancer2",
                      "status": "active",
                      "version": 1
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "description": "Provides information on the current load balancing activations.\n",
                  "additionalProperties": false,
                  "properties": {
                    "originId": {
                      "type": "string",
                      "description": "The conditional origin's unique identifier for the current load balancing activation on either or both the `PRODUCTION` and `STAGING` networks.\n"
                    },
                    "PRODUCTION": {
                      "description": "Contains information for current load balancing activations on the `PRODUCTION` network.\n",
                      "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "description": "Contains information for the current load balancing activations on either or both the `PRODUCTION` and `STAGING` networks.\n",
                        "properties": {
                          "activatedBy": {
                            "type": "string",
                            "description": "The name of the user who activated the load balancing configuration.\n"
                          },
                          "activatedDate": {
                            "format": "date-time",
                            "type": "string",
                            "description": "The date and time, in ISO 8601 format, on which the load balancing configuration was activated.\n"
                          },
                          "network": {
                            "enum": [
                              "STAGING",
                              "PRODUCTION"
                            ],
                            "type": "string",
                            "description": "The network, either `STAGING` or `PRODUCTION`, on which a load balancing configuration for Application Load Balancer has been activated.\n"
                          },
                          "originId": {
                            "type": "string",
                            "description": "The conditional origin's unique identifier.\n"
                          },
                          "status": {
                            "enum": [
                              "active"
                            ],
                            "type": "string",
                            "description": "The activation status for load balancing configuration. An `active` status indicates that the load balancing version is currently active (published) and its associated property version is also active.\n"
                          },
                          "version": {
                            "type": "integer",
                            "description": "The version number of the activated load balancing configuration.\n"
                          }
                        }
                      },
                      "type": "array"
                    },
                    "STAGING": {
                      "description": "Contains information for current load balancing activations on the `STAGING` network.\n",
                      "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "description": "Contains information for the current load balancing activations on either or both the `PRODUCTION` and `STAGING` networks.\n",
                        "properties": {
                          "activatedBy": {
                            "type": "string",
                            "description": "The name of the user who activated the load balancing configuration.\n"
                          },
                          "activatedDate": {
                            "format": "date-time",
                            "type": "string",
                            "description": "The date and time, in ISO 8601 format, on which the load balancing configuration was activated.\n"
                          },
                          "network": {
                            "enum": [
                              "STAGING",
                              "PRODUCTION"
                            ],
                            "type": "string",
                            "description": "The network, either `STAGING` or `PRODUCTION`, on which a load balancing configuration for Application Load Balancer has been activated.\n"
                          },
                          "originId": {
                            "type": "string",
                            "description": "The conditional origin's unique identifier.\n"
                          },
                          "status": {
                            "enum": [
                              "active"
                            ],
                            "type": "string",
                            "description": "The activation status for load balancing configuration. An `active` status indicates that the load balancing version is currently active (published) and its associated property version is also active.\n"
                          },
                          "version": {
                            "type": "integer",
                            "description": "The version number of the activated load balancing configuration.\n"
                          }
                        }
                      },
                      "type": "array"
                    }
                  }
                }
              }
            },
            "description": "Schema for all current load balancer activations.\n"
          }
        }
      }
    },
    "/origins/{originId}/activations": {
      "get": {
        "operationId": "get-origin-activations",
        "summary": "List activations for a load balancing configuration",
        "tags": [
          "Load balancing activations"
        ],
        "description": "The response lists the activations by the `activatedDate` with the most recent listed first.\n",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": [
                  {
                    "activatedBy": "afero",
                    "activatedDate": "2018-01-02T00:00:00.000Z",
                    "network": "PRODUCTION",
                    "originId": "loadBalancer1",
                    "status": "active",
                    "version": 1
                  },
                  {
                    "activatedBy": "szhang",
                    "activatedDate": "2018-01-01T00:00:00.000Z",
                    "network": "STAGING",
                    "originId": "loadBalancer1",
                    "status": "active",
                    "version": 2
                  }
                ],
                "schema": {
                  "items": {
                    "type": "object",
                    "required": [
                      "network",
                      "version"
                    ],
                    "additionalProperties": false,
                    "description": "Schema for a load balancer activation.\n",
                    "properties": {
                      "activatedBy": {
                        "type": "string",
                        "description": "The name of the user who activated the load balancing configuration.\n"
                      },
                      "activatedDate": {
                        "format": "date-time",
                        "type": "string",
                        "description": "The date and time, in ISO 8601 format, on which the load balancing configuration was activated.\n"
                      },
                      "dryrun": {
                        "type": "boolean",
                        "description": "If `true`, the operation validates the configuration, but does not activate the load balancing version. The default setting is `false`.\n"
                      },
                      "network": {
                        "enum": [
                          "STAGING",
                          "PRODUCTION",
                          "prod",
                          "staging",
                          "production"
                        ],
                        "type": "string",
                        "description": "The network, either `STAGING`, `PRODUCTION`, or `prod` as shorthand, on which a load balancing configuration for Application Load Balancer has been activated. Values are case-insensitive in requests.\n"
                      },
                      "originId": {
                        "type": "string",
                        "description": "The conditional origin's unique identifier.\n"
                      },
                      "status": {
                        "enum": [
                          "inactive",
                          "active",
                          "deactivated",
                          "pending",
                          "failed"
                        ],
                        "type": "string",
                        "description": "The activation status for the policy or property. Values include the following: `inactive` where the policy version has not been activated. No active property versions reference this policy. An `active` value means the policy version is currently active (published) and its associated property version is also active. A `deactivated` value means the policy version was previously activated but it has been superseded by a more recent activation of another policy version. A `pending` value means the policy version is proceeding through the activation workflow. Otherwise the value is `failed` if a problem occurs.\n"
                      },
                      "version": {
                        "minimum": 0,
                        "type": "integer",
                        "description": "The version number of the activated load balancing configuration.\n"
                      }
                    }
                  },
                  "type": "array",
                  "description": "List of current load balancing activations on `STAGING`, and `PRODUCTION` networks.\n"
                }
              }
            },
            "description": "Schema for a list of load balancer activations.\n"
          }
        }
      },
      "parameters": [
        {
          "description": "Unique identifier for the origin.\n",
          "in": "path",
          "name": "originId",
          "required": true,
          "schema": {
            "type": "string",
            "example": "originremote2"
          }
        }
      ],
      "post": {
        "operationId": "post-origin-activations",
        "summary": "Activate a load balancing version",
        "tags": [
          "Load balancing activations"
        ],
        "description": "Activate the selected load balancing version. The load balancing version status is either `active` or `inactive`.\n",
        "parameters": [
          {
            "description": "Set `async` to `true` for policy activations on multiple properties to reduce API response time and let the policy activation continue asynchronously in the background. Default is `false`.\n",
            "in": "query",
            "name": "async",
            "schema": {
              "default": false,
              "example": true,
              "type": "boolean"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "dryrun": false,
                "network": "PRODUCTION",
                "version": 1
              },
              "schema": {
                "type": "object",
                "description": "TBD.\n",
                "required": [
                  "network",
                  "version"
                ],
                "additionalProperties": false,
                "properties": {
                  "dryrun": {
                    "type": "boolean",
                    "description": "If `true`, the operation validates the configuration, but does not activate the load balancing version. The default setting is `false`.\n"
                  },
                  "network": {
                    "enum": [
                      "STAGING",
                      "PRODUCTION",
                      "prod",
                      "staging",
                      "production"
                    ],
                    "type": "string",
                    "description": "The network, either `STAGING`, `PRODUCTION`, or `prod` as shorthand, on which a load balancing configuration for Application Load Balancer has been activated. Values are case-insensitive in requests.\n"
                  },
                  "version": {
                    "minimum": 0,
                    "type": "integer",
                    "description": "The version number of the activated load balancing configuration.\n"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "activatedBy": "adevi",
                  "activatedDate": "2018-01-02T00:00:00.000Z",
                  "dryrun": false,
                  "network": "PRODUCTION",
                  "originId": "loadBalancer1",
                  "status": "active",
                  "version": 1
                },
                "schema": {
                  "type": "object",
                  "description": "Details to activate a specific load balancing version on the `network` you select.\n",
                  "required": [
                    "network",
                    "version"
                  ],
                  "additionalProperties": false,
                  "properties": {
                    "activatedBy": {
                      "type": "string",
                      "description": "The name of the user who activated the load balancing configuration.\n"
                    },
                    "activatedDate": {
                      "format": "date-time",
                      "type": "string",
                      "description": "The date and time, in ISO 8601 format, on which the load balancing configuration was activated.\n"
                    },
                    "dryrun": {
                      "type": "boolean",
                      "description": "If `true`, the operation validates the configuration, but does not activate the load balancing version. The default setting is `false`.\n"
                    },
                    "network": {
                      "enum": [
                        "STAGING",
                        "PRODUCTION",
                        "prod",
                        "staging",
                        "production"
                      ],
                      "type": "string",
                      "description": "The network, either `STAGING`, `PRODUCTION`, or `prod` as shorthand, on which a load balancing configuration for Application Load Balancer has been activated. Values are case-insensitive in requests.\n"
                    },
                    "originId": {
                      "type": "string",
                      "description": "The conditional origin's unique identifier.\n"
                    },
                    "status": {
                      "enum": [
                        "inactive",
                        "active",
                        "deactivated",
                        "pending",
                        "failed"
                      ],
                      "type": "string",
                      "description": "The activation status for the load balancing version. Values include the following: `inactive` where the load balancing version has not been activated. No active property versions reference this policy. A value of `active` means the load balancing version is currently active (published) and its associated property version is also active. A `deactivated` value means the load balancing version was previously activated but it has been superseded by a more recent activation of another load balancing version. A `pending` value means the load balancing version is proceeding through the activation workflow. Otherwise the value is `failed` if a problem occurs.\n"
                    },
                    "version": {
                      "minimum": 0,
                      "type": "integer",
                      "description": "The version number of the activated load balancing configuration.\n"
                    }
                  }
                }
              }
            },
            "description": "Schema for a load balancer activation.\n"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "origin-currentactivations": {
        "type": "object",
        "additionalProperties": false,
        "description": "Contains information for the current load balancing activations on either or both the `PRODUCTION` and `STAGING` networks.\n",
        "properties": {
          "activatedBy": {
            "type": "string",
            "description": "The name of the user who activated the load balancing configuration.\n"
          },
          "activatedDate": {
            "format": "date-time",
            "type": "string",
            "description": "The date and time, in ISO 8601 format, on which the load balancing configuration was activated.\n"
          },
          "network": {
            "enum": [
              "STAGING",
              "PRODUCTION"
            ],
            "type": "string",
            "description": "The network, either `STAGING` or `PRODUCTION`, on which a load balancing configuration for Application Load Balancer has been activated.\n"
          },
          "originId": {
            "type": "string",
            "description": "The conditional origin's unique identifier.\n"
          },
          "status": {
            "enum": [
              "active"
            ],
            "type": "string",
            "description": "The activation status for load balancing configuration. An `active` status indicates that the load balancing version is currently active (published) and its associated property version is also active.\n"
          },
          "version": {
            "type": "integer",
            "description": "The version number of the activated load balancing configuration.\n"
          }
        }
      },
      "get-origins-currentactivations-response": {
        "type": "object",
        "description": "Provides information on the current load balancing activations.\n",
        "additionalProperties": false,
        "properties": {
          "originId": {
            "type": "string",
            "description": "The conditional origin's unique identifier for the current load balancing activation on either or both the `PRODUCTION` and `STAGING` networks.\n"
          },
          "PRODUCTION": {
            "description": "Contains information for current load balancing activations on the `PRODUCTION` network.\n",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "description": "Contains information for the current load balancing activations on either or both the `PRODUCTION` and `STAGING` networks.\n",
              "properties": {
                "activatedBy": {
                  "type": "string",
                  "description": "The name of the user who activated the load balancing configuration.\n"
                },
                "activatedDate": {
                  "format": "date-time",
                  "type": "string",
                  "description": "The date and time, in ISO 8601 format, on which the load balancing configuration was activated.\n"
                },
                "network": {
                  "enum": [
                    "STAGING",
                    "PRODUCTION"
                  ],
                  "type": "string",
                  "description": "The network, either `STAGING` or `PRODUCTION`, on which a load balancing configuration for Application Load Balancer has been activated.\n"
                },
                "originId": {
                  "type": "string",
                  "description": "The conditional origin's unique identifier.\n"
                },
                "status": {
                  "enum": [
                    "active"
                  ],
                  "type": "string",
                  "description": "The activation status for load balancing configuration. An `active` status indicates that the load balancing version is currently active (published) and its associated property version is also active.\n"
                },
                "version": {
                  "type": "integer",
                  "description": "The version number of the activated load balancing configuration.\n"
                }
              }
            },
            "type": "array"
          },
          "STAGING": {
            "description": "Contains information for current load balancing activations on the `STAGING` network.\n",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "description": "Contains information for the current load balancing activations on either or both the `PRODUCTION` and `STAGING` networks.\n",
              "properties": {
                "activatedBy": {
                  "type": "string",
                  "description": "The name of the user who activated the load balancing configuration.\n"
                },
                "activatedDate": {
                  "format": "date-time",
                  "type": "string",
                  "description": "The date and time, in ISO 8601 format, on which the load balancing configuration was activated.\n"
                },
                "network": {
                  "enum": [
                    "STAGING",
                    "PRODUCTION"
                  ],
                  "type": "string",
                  "description": "The network, either `STAGING` or `PRODUCTION`, on which a load balancing configuration for Application Load Balancer has been activated.\n"
                },
                "originId": {
                  "type": "string",
                  "description": "The conditional origin's unique identifier.\n"
                },
                "status": {
                  "enum": [
                    "active"
                  ],
                  "type": "string",
                  "description": "The activation status for load balancing configuration. An `active` status indicates that the load balancing version is currently active (published) and its associated property version is also active.\n"
                },
                "version": {
                  "type": "integer",
                  "description": "The version number of the activated load balancing configuration.\n"
                }
              }
            },
            "type": "array"
          }
        }
      },
      "origin-activation": {
        "type": "object",
        "required": [
          "network",
          "version"
        ],
        "additionalProperties": false,
        "description": "Schema for a load balancer activation.\n",
        "properties": {
          "activatedBy": {
            "type": "string",
            "description": "The name of the user who activated the load balancing configuration.\n"
          },
          "activatedDate": {
            "format": "date-time",
            "type": "string",
            "description": "The date and time, in ISO 8601 format, on which the load balancing configuration was activated.\n"
          },
          "dryrun": {
            "type": "boolean",
            "description": "If `true`, the operation validates the configuration, but does not activate the load balancing version. The default setting is `false`.\n"
          },
          "network": {
            "enum": [
              "STAGING",
              "PRODUCTION",
              "prod",
              "staging",
              "production"
            ],
            "type": "string",
            "description": "The network, either `STAGING`, `PRODUCTION`, or `prod` as shorthand, on which a load balancing configuration for Application Load Balancer has been activated. Values are case-insensitive in requests.\n"
          },
          "originId": {
            "type": "string",
            "description": "The conditional origin's unique identifier.\n"
          },
          "status": {
            "enum": [
              "inactive",
              "active",
              "deactivated",
              "pending",
              "failed"
            ],
            "type": "string",
            "description": "The activation status for the policy or property. Values include the following: `inactive` where the policy version has not been activated. No active property versions reference this policy. An `active` value means the policy version is currently active (published) and its associated property version is also active. A `deactivated` value means the policy version was previously activated but it has been superseded by a more recent activation of another policy version. A `pending` value means the policy version is proceeding through the activation workflow. Otherwise the value is `failed` if a problem occurs.\n"
          },
          "version": {
            "minimum": 0,
            "type": "integer",
            "description": "The version number of the activated load balancing configuration.\n"
          }
        }
      },
      "get-origin-activations-response": {
        "items": {
          "type": "object",
          "required": [
            "network",
            "version"
          ],
          "additionalProperties": false,
          "description": "Schema for a load balancer activation.\n",
          "properties": {
            "activatedBy": {
              "type": "string",
              "description": "The name of the user who activated the load balancing configuration.\n"
            },
            "activatedDate": {
              "format": "date-time",
              "type": "string",
              "description": "The date and time, in ISO 8601 format, on which the load balancing configuration was activated.\n"
            },
            "dryrun": {
              "type": "boolean",
              "description": "If `true`, the operation validates the configuration, but does not activate the load balancing version. The default setting is `false`.\n"
            },
            "network": {
              "enum": [
                "STAGING",
                "PRODUCTION",
                "prod",
                "staging",
                "production"
              ],
              "type": "string",
              "description": "The network, either `STAGING`, `PRODUCTION`, or `prod` as shorthand, on which a load balancing configuration for Application Load Balancer has been activated. Values are case-insensitive in requests.\n"
            },
            "originId": {
              "type": "string",
              "description": "The conditional origin's unique identifier.\n"
            },
            "status": {
              "enum": [
                "inactive",
                "active",
                "deactivated",
                "pending",
                "failed"
              ],
              "type": "string",
              "description": "The activation status for the policy or property. Values include the following: `inactive` where the policy version has not been activated. No active property versions reference this policy. An `active` value means the policy version is currently active (published) and its associated property version is also active. A `deactivated` value means the policy version was previously activated but it has been superseded by a more recent activation of another policy version. A `pending` value means the policy version is proceeding through the activation workflow. Otherwise the value is `failed` if a problem occurs.\n"
            },
            "version": {
              "minimum": 0,
              "type": "integer",
              "description": "The version number of the activated load balancing configuration.\n"
            }
          }
        },
        "type": "array",
        "description": "List of current load balancing activations on `STAGING`, and `PRODUCTION` networks.\n"
      },
      "post-origin-activations-request": {
        "type": "object",
        "description": "TBD.\n",
        "required": [
          "network",
          "version"
        ],
        "additionalProperties": false,
        "properties": {
          "dryrun": {
            "type": "boolean",
            "description": "If `true`, the operation validates the configuration, but does not activate the load balancing version. The default setting is `false`.\n"
          },
          "network": {
            "enum": [
              "STAGING",
              "PRODUCTION",
              "prod",
              "staging",
              "production"
            ],
            "type": "string",
            "description": "The network, either `STAGING`, `PRODUCTION`, or `prod` as shorthand, on which a load balancing configuration for Application Load Balancer has been activated. Values are case-insensitive in requests.\n"
          },
          "version": {
            "minimum": 0,
            "type": "integer",
            "description": "The version number of the activated load balancing configuration.\n"
          }
        }
      },
      "post-origin-activations-response": {
        "type": "object",
        "description": "Details to activate a specific load balancing version on the `network` you select.\n",
        "required": [
          "network",
          "version"
        ],
        "additionalProperties": false,
        "properties": {
          "activatedBy": {
            "type": "string",
            "description": "The name of the user who activated the load balancing configuration.\n"
          },
          "activatedDate": {
            "format": "date-time",
            "type": "string",
            "description": "The date and time, in ISO 8601 format, on which the load balancing configuration was activated.\n"
          },
          "dryrun": {
            "type": "boolean",
            "description": "If `true`, the operation validates the configuration, but does not activate the load balancing version. The default setting is `false`.\n"
          },
          "network": {
            "enum": [
              "STAGING",
              "PRODUCTION",
              "prod",
              "staging",
              "production"
            ],
            "type": "string",
            "description": "The network, either `STAGING`, `PRODUCTION`, or `prod` as shorthand, on which a load balancing configuration for Application Load Balancer has been activated. Values are case-insensitive in requests.\n"
          },
          "originId": {
            "type": "string",
            "description": "The conditional origin's unique identifier.\n"
          },
          "status": {
            "enum": [
              "inactive",
              "active",
              "deactivated",
              "pending",
              "failed"
            ],
            "type": "string",
            "description": "The activation status for the load balancing version. Values include the following: `inactive` where the load balancing version has not been activated. No active property versions reference this policy. A value of `active` means the load balancing version is currently active (published) and its associated property version is also active. A `deactivated` value means the load balancing version was previously activated but it has been superseded by a more recent activation of another load balancing version. A `pending` value means the load balancing version is proceeding through the activation workflow. Otherwise the value is `failed` if a problem occurs.\n"
          },
          "version": {
            "minimum": 0,
            "type": "integer",
            "description": "The version number of the activated load balancing configuration.\n"
          }
        }
      }
    },
    "parameters": {
      "originId-path": {
        "description": "Unique identifier for the origin.\n",
        "in": "path",
        "name": "originId",
        "required": true,
        "schema": {
          "type": "string",
          "example": "originremote2"
        }
      },
      "async-query": {
        "description": "Set `async` to `true` for policy activations on multiple properties to reduce API response time and let the policy activation continue asynchronously in the background. Default is `false`.\n",
        "in": "query",
        "name": "async",
        "schema": {
          "default": false,
          "example": true,
          "type": "boolean"
        }
      }
    }
  },
  "x-akamai": {
    "auth-type": "EDGE_GRID"
  }
}