{
  "openapi": "3.0.0",
  "info": {
    "title": "Properties",
    "version": "3",
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "servers": [
    {
      "url": "https://{hostname}/identity-management/v3"
    }
  ],
  "tags": [
    {
      "description": "Fetch properties and includes used by an account with their details,\nincluding their users.\n",
      "name": "Assets"
    },
    {
      "description": "Fetch resources used by a property or include.\n",
      "name": "Resources"
    }
  ],
  "paths": {
    "/user-admin/properties": {
      "x-akamai": {
        "file-path": "paths/properties.yaml",
        "path-info": "/user-admin/properties"
      },
      "get": {
        "operationId": "get-properties",
        "summary": "List properties or includes",
        "tags": [
          "Assets"
        ],
        "description": "This operation lists the properties and includes for the current account or other managed accounts using the `accountSwitchKey` parameter. Include the `groupId` parameter in your request to filter the results by group. The response returns a list of `propertyId` regardless of whether they represent a property or include in PAPI. To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
        "parameters": [
          {
            "name": "groupId",
            "in": "query",
            "description": "Unique identifier for each group. To get this value, run the [List groups](ref:get-groups) operation.",
            "x-akamai": {
              "file-path": "parameters/group-id-opt-group-id.yaml"
            },
            "schema": {
              "type": "integer",
              "example": 54321
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The response provides the assets.\n",
            "content": {
              "application/json": {
                "example": [
                  {
                    "groupName": "Digital Company",
                    "groupId": 12345,
                    "propertyId": 99999999,
                    "propertyTypeDescription": "On Demand Media",
                    "propertyName": "0rb-digital-company-01.com",
                    "actions": {
                      "move": true
                    }
                  },
                  {
                    "groupName": "Internet Company",
                    "groupId": 32145,
                    "propertyId": 88888888,
                    "propertyTypeDescription": "On Demand Media",
                    "propertyName": "0rb-internet-company-01.com",
                    "actions": {
                      "move": true
                    }
                  }
                ],
                "schema": {
                  "description": "Encapsulates information about each property.\n",
                  "items": {
                    "additionalProperties": false,
                    "description": "Encapsulates information about an asset.\n",
                    "properties": {
                      "actions": {
                        "additionalProperties": false,
                        "description": "Specifies activities available for the group.\n",
                        "properties": {
                          "move": {
                            "description": "Whether you can move a asset from one group to another group.\n",
                            "type": "boolean"
                          }
                        },
                        "required": [
                          "move"
                        ],
                        "type": "object"
                      },
                      "groupId": {
                        "description": "Unique identifier for each group. It filters down results to properties in the specified group.\n",
                        "minimum": 0,
                        "type": "integer"
                      },
                      "groupName": {
                        "description": "Descriptive label for the group.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "propertyId": {
                        "description": "Unique identifier for a property or include. This is what [PAPI](https://techdocs.akamai.com/property-mgr/reference/get-properties) refers to as an `assetId`. Note thereâ€™s a discrepancy between how PAPI and Identity and Access Management refer to `propertyId` values. To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
                        "minimum": 0,
                        "type": "integer"
                      },
                      "propertyName": {
                        "description": "Name of the property [created in PAPI](https://techdocs.akamai.com/property-mgr/reference/post-properties), or the `includeName` when [creating an include](https://techdocs.akamai.com/property-mgr/reference/post-includes). To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "propertyTypeDescription": {
                        "description": "Identifies the product-type such as `On Demand Media`, `Site`, `Application`, `Live Media Streams`, or `NetStorage`.\n",
                        "minLength": 1,
                        "type": "string"
                      }
                    },
                    "required": [
                      "propertyId",
                      "groupId",
                      "groupName",
                      "propertyName",
                      "propertyTypeDescription"
                    ],
                    "type": "object",
                    "x-akamai": {
                      "file-path": "schemas/property-list-item.yaml"
                    }
                  },
                  "minItems": 0,
                  "type": "array",
                  "x-akamai": {
                    "file-path": "schemas/list-of-property-list-item.yaml"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user-admin/properties/{assetId}": {
      "x-akamai": {
        "file-path": "paths/property.yaml",
        "path-info": "/user-admin/properties/{assetId}"
      },
      "parameters": [
        {
          "name": "assetId",
          "in": "path",
          "description": "Unique identifier for each asset, either a property or an include. To get this value, run the [List properties or includes](ref:get-properties) operation.",
          "x-akamai": {
            "file-path": "parameters/asset-id-path.yaml"
          },
          "required": true,
          "schema": {
            "type": "integer",
            "example": 9678999
          }
        }
      ],
      "get": {
        "operationId": "get-property",
        "summary": "Get a property or include",
        "tags": [
          "Assets"
        ],
        "description": "This operation fetches a property's or include's details. The response returns details for `propertyId` regardless of whether it represent a property or include in PAPI. To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
        "parameters": [
          {
            "name": "groupId",
            "in": "query",
            "description": "Unique identifier for each group. To get this value, run the [List groups](ref:get-groups) operation.",
            "x-akamai": {
              "file-path": "parameters/group-id-req-qp-group-id.yaml"
            },
            "required": true,
            "schema": {
              "type": "integer",
              "example": 32145
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The response provides the asset's details.\n",
            "content": {
              "application/json": {
                "example": {
                  "createdDate": "2017-07-27T18:11:25.000Z",
                  "createdBy": "afero@example.com",
                  "modifiedDate": "2017-07-27T18:11:25.000Z",
                  "modifiedBy": "adevi@example.com",
                  "groupName": "Sales Team",
                  "groupId": 12345,
                  "arlConfigFile": "0rb-internet-company-01.com.xml",
                  "propertyId": 9678999,
                  "propertyName": "0rb-internet-company-01.com"
                },
                "schema": {
                  "additionalProperties": false,
                  "description": "Encapsulates information about an asset.\n",
                  "properties": {
                    "arlConfigFile": {
                      "description": "An ARL (Akamai resource locator) configuration file, specifying versions of an object you can't purge using the URL. The `arlConfigFile` is the same as the `propertyName` with an `xml` extension.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "createdBy": {
                      "description": "The user who created the asset.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "createdDate": {
                      "description": "ISO 8601 timestamp indicating when the asset was originally created.\n",
                      "format": "date-time",
                      "type": "string"
                    },
                    "groupId": {
                      "description": "Unique identifier for each group. It filters down results to properties in the specified group.\n",
                      "minimum": 0,
                      "type": "integer"
                    },
                    "groupName": {
                      "description": "Descriptive label for the group.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "modifiedBy": {
                      "description": "The user who last edited the asset.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "modifiedDate": {
                      "description": "ISO 8601 timestamp indicating when the asset was last updated.\n",
                      "format": "date-time",
                      "type": "string"
                    },
                    "propertyId": {
                      "description": "Unique identifier for a property or include. This is what [PAPI](https://techdocs.akamai.com/property-mgr/reference/get-properties) refers to as an `assetId`. Note thereâ€™s a discrepancy between how PAPI and Identity and Access Management refer to `propertyId` values. To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
                      "minimum": 0,
                      "type": "integer"
                    },
                    "propertyName": {
                      "description": "Name of the property [created in PAPI](https://techdocs.akamai.com/property-mgr/reference/post-properties), or the `includeName` when [creating an include](https://techdocs.akamai.com/property-mgr/reference/post-includes). To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [
                    "createdDate",
                    "createdBy",
                    "modifiedDate",
                    "modifiedBy",
                    "groupName",
                    "groupId",
                    "arlConfigFile",
                    "propertyId",
                    "propertyName"
                  ],
                  "type": "object",
                  "x-akamai": {
                    "file-path": "schemas/property-response.yaml"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "operationId": "put-property",
        "summary": "Move a property or include",
        "tags": [
          "Assets"
        ],
        "description": "This operation moves a property or include from one group to another group. You can only move an asset into another group within the same group hierarchy. Depending on your role in the destination group, you may lose access to resources the asset uses. Before moving an asset, run the [List users affected by moving a group](ref:get-move-affected-users) operation to review which users will be affected by the move.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "sourceGroupId": 11111,
                "destinationGroupId": 22222
              },
              "schema": {
                "additionalProperties": false,
                "description": "Describes the request body for moving a property under another group.\n",
                "properties": {
                  "destinationGroupId": {
                    "description": "Identifies the group where you want to move the `sourceGroupId` within the same parent hierarchy. To get this value, run the [List groups](ref:get-groups) operation.\n",
                    "minimum": 0,
                    "type": "integer"
                  },
                  "sourceGroupId": {
                    "description": "Identifies the group from which you want to move the asset. To get this value, run the [List properties or includes](ref:get-properties) operation.\n",
                    "minimum": 0,
                    "type": "integer"
                  }
                },
                "required": [
                  "sourceGroupId",
                  "destinationGroupId"
                ],
                "type": "object",
                "x-akamai": {
                  "file-path": "schemas/move-property-request.yaml"
                }
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Asset successfully moved.\n"
          }
        }
      }
    },
    "/user-admin/properties/{assetId}/resources": {
      "x-akamai": {
        "file-path": "paths/resources.yaml",
        "path-info": "/user-admin/properties/{assetId}/resources"
      },
      "parameters": [
        {
          "name": "assetId",
          "in": "path",
          "description": "Unique identifier for each asset, either a property or an include. To get this value, run the [List properties or includes](ref:get-properties) operation.",
          "x-akamai": {
            "file-path": "parameters/asset-id-path.yaml"
          },
          "required": true,
          "schema": {
            "type": "integer",
            "example": 9678999
          }
        }
      ],
      "get": {
        "operationId": "get-property-resources",
        "summary": "Get asset's resources",
        "tags": [
          "Resources"
        ],
        "description": "This operation lists resources a property or include uses to deliver your web content across Akamai's edge network. You can think of these resources as objects, like CP codes and configuration files. For example, an ARL (Akamai resource locator) configuration file specifies how Akamai purges versions of an object that you canâ€™t purge using just the URL.\n",
        "parameters": [
          {
            "name": "groupId",
            "in": "query",
            "description": "Unique identifier for each group. To get this value, run the [List groups](ref:get-groups) operation.",
            "x-akamai": {
              "file-path": "parameters/group-id-req-qp-group-id.yaml"
            },
            "required": true,
            "schema": {
              "type": "integer",
              "example": 32145
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The response provides the resources.\n",
            "content": {
              "application/json": {
                "example": [
                  {
                    "resourceId": 111111,
                    "resourceType": "arlfile",
                    "resourceName": "0rb-internet-company-01.com.xml",
                    "modifiedDate": "2017-09-07T17:00:58.000Z"
                  },
                  {
                    "resourceId": 8988898,
                    "resourceType": "cpcode",
                    "resourceName": "mycpcode(123456)",
                    "modifiedDate": "2017-04-24T16:19:27.000Z"
                  }
                ],
                "schema": {
                  "description": "Encapsulates information about resources.\n",
                  "items": {
                    "additionalProperties": false,
                    "description": "Encapsulates information about resources.\n",
                    "properties": {
                      "modifiedDate": {
                        "description": "ISO 8601 timestamp indicating when the resource was last updated.\n",
                        "format": "date-time",
                        "type": "string"
                      },
                      "resourceId": {
                        "description": "Unique identifier for each resource.\n",
                        "minimum": 0,
                        "type": "integer"
                      },
                      "resourceName": {
                        "description": "Descriptive label for the resource.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "resourceType": {
                        "description": "Helps to characterize a asset's resource, either `cname`, `arlfile`, `cpcode`, `storagegroup`, `fpdomain`, or `edns`. For more information, see [View property details](https://techdocs.akamai.com/iam/docs/mng-properties).\n",
                        "enum": [
                          "enable",
                          "arlfile",
                          "cpcode",
                          "storagegroup",
                          "fpdomain",
                          "edns"
                        ],
                        "minLength": 1,
                        "type": "string"
                      }
                    },
                    "required": [
                      "resourceId",
                      "resourceType",
                      "resourceName",
                      "modifiedDate"
                    ],
                    "type": "object",
                    "x-akamai": {
                      "file-path": "schemas/resource-item.yaml"
                    }
                  },
                  "minItems": 0,
                  "type": "array",
                  "x-akamai": {
                    "file-path": "schemas/list-of-resource-item.yaml"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user-admin/properties/{assetId}/users": {
      "x-akamai": {
        "file-path": "paths/users-property.yaml",
        "path-info": "/user-admin/properties/{assetId}/users"
      },
      "parameters": [
        {
          "name": "assetId",
          "in": "path",
          "description": "Unique identifier for each asset, either a property or an include. To get this value, run the [List properties or includes](ref:get-properties) operation.",
          "x-akamai": {
            "file-path": "parameters/asset-id-path.yaml"
          },
          "required": true,
          "schema": {
            "type": "integer",
            "example": 9678999
          }
        }
      ],
      "get": {
        "operationId": "get-property-users",
        "summary": "List users for property or include",
        "tags": [
          "Assets"
        ],
        "description": "This operation lists users who can access a property or include.\n",
        "parameters": [
          {
            "name": "userType",
            "in": "query",
            "description": "Filters the list by users who have `lostAccess` or the reverse `gainAccess`.",
            "x-akamai": {
              "file-path": "parameters/user-type-query.yaml"
            },
            "schema": {
              "type": "string",
              "example": "lostAccess",
              "enum": [
                "lostAccess",
                "gainAccess"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The response provides the users accessing the property or include.\n",
            "content": {
              "application/json": {
                "example": [
                  {
                    "uiUserName": "szhang",
                    "uiIdentityId": "B-3-146FAB9",
                    "firstName": "Media",
                    "lastName": "QA",
                    "isBlocked": true
                  },
                  {
                    "uiUserName": "mrossi",
                    "uiIdentityId": "B-C-IP9IND",
                    "firstName": "Bert",
                    "lastName": "Moody",
                    "isBlocked": false
                  }
                ],
                "schema": {
                  "description": "Encapsulates all the users of a property by property ID.\n",
                  "items": {
                    "additionalProperties": false,
                    "description": "Encapsulates all the users of a property by property ID.\n",
                    "properties": {
                      "firstName": {
                        "description": "The user's first name.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "isBlocked": {
                        "description": "Whether a user's access to an asset is blocked.\n",
                        "type": "boolean"
                      },
                      "lastName": {
                        "description": "The user's surname.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "uiIdentityId": {
                        "description": "Unique identifier for each user, which corresponds to their Control Center profile or client ID. Also known as a `contactId` in other APIs.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "uiUserName": {
                        "description": "The user's username in Control Center.\n",
                        "minLength": 1,
                        "type": "string"
                      }
                    },
                    "required": [
                      "uiUserName",
                      "uiIdentityId",
                      "firstName",
                      "lastName",
                      "isBlocked"
                    ],
                    "type": "object",
                    "x-akamai": {
                      "file-path": "schemas/user-property-id.yaml"
                    }
                  },
                  "minItems": 0,
                  "type": "array",
                  "x-akamai": {
                    "file-path": "schemas/users-of-property-response.yaml"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user-admin/properties/{assetId}/users/block": {
      "x-akamai": {
        "file-path": "paths/block.yaml",
        "path-info": "/user-admin/properties/{assetId}/users/block"
      },
      "parameters": [
        {
          "name": "assetId",
          "in": "path",
          "description": "Unique identifier for each asset, either a property or an include. To get this value, run the [List properties or includes](ref:get-properties) operation.",
          "x-akamai": {
            "file-path": "parameters/asset-id-path.yaml"
          },
          "required": true,
          "schema": {
            "type": "integer",
            "example": 9678999
          }
        }
      ],
      "put": {
        "operationId": "put-property-users-block",
        "summary": "Block users from a property or include",
        "tags": [
          "Assets"
        ],
        "description": "This operation blocks the users on a property or include.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": [
                {
                  "uiIdentityId": "B-3-146FAB9"
                },
                {
                  "uiIdentityId": "B-C-IP9IND"
                }
              ],
              "schema": {
                "description": "Encapsulates all the users who needs to be blocked based on UI identities.\n",
                "items": {
                  "additionalProperties": false,
                  "description": "Encapsulates all the users who needs to be blocked based on UI identities.\n",
                  "properties": {
                    "uiIdentityId": {
                      "description": "Unique identifier for each user, which corresponds to their Control Center profile or client ID. Also known as a `contactId` in other APIs. To get this value, run the [List users for property or include](ref:get-property-users) operation.\n",
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [
                    "uiIdentityId"
                  ],
                  "type": "object",
                  "x-akamai": {
                    "file-path": "schemas/user-block-uiidentities.yaml"
                  }
                },
                "minItems": 0,
                "type": "array",
                "x-akamai": {
                  "file-path": "schemas/users-block-uiidentities.yaml"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The response provides the users blocked from the asset.\n",
            "content": {
              "application/json": {
                "example": [
                  {
                    "uiUserName": "szhang",
                    "uiIdentityId": "B-3-146FAB9",
                    "firstName": "Media",
                    "lastName": "QA",
                    "isBlocked": true
                  },
                  {
                    "uiUserName": "mrossi",
                    "uiIdentityId": "B-C-IP9IND",
                    "firstName": "Bert",
                    "lastName": "Moody",
                    "isBlocked": false
                  }
                ],
                "schema": {
                  "description": "Encapsulates all the users of a property by property ID.\n",
                  "items": {
                    "additionalProperties": false,
                    "description": "Encapsulates all the users of a property by property ID.\n",
                    "properties": {
                      "firstName": {
                        "description": "The user's first name.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "isBlocked": {
                        "description": "Whether a user's access to an asset is blocked.\n",
                        "type": "boolean"
                      },
                      "lastName": {
                        "description": "The user's surname.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "uiIdentityId": {
                        "description": "Unique identifier for each user, which corresponds to their Control Center profile or client ID. Also known as a `contactId` in other APIs.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "uiUserName": {
                        "description": "The user's username in Control Center.\n",
                        "minLength": 1,
                        "type": "string"
                      }
                    },
                    "required": [
                      "uiUserName",
                      "uiIdentityId",
                      "firstName",
                      "lastName",
                      "isBlocked"
                    ],
                    "type": "object",
                    "x-akamai": {
                      "file-path": "schemas/user-property-id.yaml"
                    }
                  },
                  "minItems": 0,
                  "type": "array",
                  "x-akamai": {
                    "file-path": "schemas/users-of-property-response.yaml"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "group-id-opt-group-id": {
        "name": "groupId",
        "in": "query",
        "description": "Unique identifier for each group. To get this value, run the [List groups](ref:get-groups) operation.",
        "x-akamai": {
          "file-path": "parameters/group-id-opt-group-id.yaml"
        },
        "schema": {
          "type": "integer",
          "example": 54321
        }
      },
      "asset-id-path": {
        "name": "assetId",
        "in": "path",
        "description": "Unique identifier for each asset, either a property or an include. To get this value, run the [List properties or includes](ref:get-properties) operation.",
        "x-akamai": {
          "file-path": "parameters/asset-id-path.yaml"
        },
        "required": true,
        "schema": {
          "type": "integer",
          "example": 9678999
        }
      },
      "group-id-req-qp-group-id": {
        "name": "groupId",
        "in": "query",
        "description": "Unique identifier for each group. To get this value, run the [List groups](ref:get-groups) operation.",
        "x-akamai": {
          "file-path": "parameters/group-id-req-qp-group-id.yaml"
        },
        "required": true,
        "schema": {
          "type": "integer",
          "example": 32145
        }
      },
      "user-type-query": {
        "name": "userType",
        "in": "query",
        "description": "Filters the list by users who have `lostAccess` or the reverse `gainAccess`.",
        "x-akamai": {
          "file-path": "parameters/user-type-query.yaml"
        },
        "schema": {
          "type": "string",
          "example": "lostAccess",
          "enum": [
            "lostAccess",
            "gainAccess"
          ]
        }
      }
    },
    "schemas": {
      "property-list-item": {
        "additionalProperties": false,
        "description": "Encapsulates information about an asset.\n",
        "properties": {
          "actions": {
            "additionalProperties": false,
            "description": "Specifies activities available for the group.\n",
            "properties": {
              "move": {
                "description": "Whether you can move a asset from one group to another group.\n",
                "type": "boolean"
              }
            },
            "required": [
              "move"
            ],
            "type": "object"
          },
          "groupId": {
            "description": "Unique identifier for each group. It filters down results to properties in the specified group.\n",
            "minimum": 0,
            "type": "integer"
          },
          "groupName": {
            "description": "Descriptive label for the group.\n",
            "minLength": 1,
            "type": "string"
          },
          "propertyId": {
            "description": "Unique identifier for a property or include. This is what [PAPI](https://techdocs.akamai.com/property-mgr/reference/get-properties) refers to as an `assetId`. Note thereâ€™s a discrepancy between how PAPI and Identity and Access Management refer to `propertyId` values. To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
            "minimum": 0,
            "type": "integer"
          },
          "propertyName": {
            "description": "Name of the property [created in PAPI](https://techdocs.akamai.com/property-mgr/reference/post-properties), or the `includeName` when [creating an include](https://techdocs.akamai.com/property-mgr/reference/post-includes). To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
            "minLength": 1,
            "type": "string"
          },
          "propertyTypeDescription": {
            "description": "Identifies the product-type such as `On Demand Media`, `Site`, `Application`, `Live Media Streams`, or `NetStorage`.\n",
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "propertyId",
          "groupId",
          "groupName",
          "propertyName",
          "propertyTypeDescription"
        ],
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/property-list-item.yaml"
        }
      },
      "list-of-property-list-item": {
        "description": "Encapsulates information about each property.\n",
        "items": {
          "additionalProperties": false,
          "description": "Encapsulates information about an asset.\n",
          "properties": {
            "actions": {
              "additionalProperties": false,
              "description": "Specifies activities available for the group.\n",
              "properties": {
                "move": {
                  "description": "Whether you can move a asset from one group to another group.\n",
                  "type": "boolean"
                }
              },
              "required": [
                "move"
              ],
              "type": "object"
            },
            "groupId": {
              "description": "Unique identifier for each group. It filters down results to properties in the specified group.\n",
              "minimum": 0,
              "type": "integer"
            },
            "groupName": {
              "description": "Descriptive label for the group.\n",
              "minLength": 1,
              "type": "string"
            },
            "propertyId": {
              "description": "Unique identifier for a property or include. This is what [PAPI](https://techdocs.akamai.com/property-mgr/reference/get-properties) refers to as an `assetId`. Note thereâ€™s a discrepancy between how PAPI and Identity and Access Management refer to `propertyId` values. To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
              "minimum": 0,
              "type": "integer"
            },
            "propertyName": {
              "description": "Name of the property [created in PAPI](https://techdocs.akamai.com/property-mgr/reference/post-properties), or the `includeName` when [creating an include](https://techdocs.akamai.com/property-mgr/reference/post-includes). To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
              "minLength": 1,
              "type": "string"
            },
            "propertyTypeDescription": {
              "description": "Identifies the product-type such as `On Demand Media`, `Site`, `Application`, `Live Media Streams`, or `NetStorage`.\n",
              "minLength": 1,
              "type": "string"
            }
          },
          "required": [
            "propertyId",
            "groupId",
            "groupName",
            "propertyName",
            "propertyTypeDescription"
          ],
          "type": "object",
          "x-akamai": {
            "file-path": "schemas/property-list-item.yaml"
          }
        },
        "minItems": 0,
        "type": "array",
        "x-akamai": {
          "file-path": "schemas/list-of-property-list-item.yaml"
        }
      },
      "property-response": {
        "additionalProperties": false,
        "description": "Encapsulates information about an asset.\n",
        "properties": {
          "arlConfigFile": {
            "description": "An ARL (Akamai resource locator) configuration file, specifying versions of an object you can't purge using the URL. The `arlConfigFile` is the same as the `propertyName` with an `xml` extension.\n",
            "minLength": 1,
            "type": "string"
          },
          "createdBy": {
            "description": "The user who created the asset.\n",
            "minLength": 1,
            "type": "string"
          },
          "createdDate": {
            "description": "ISO 8601 timestamp indicating when the asset was originally created.\n",
            "format": "date-time",
            "type": "string"
          },
          "groupId": {
            "description": "Unique identifier for each group. It filters down results to properties in the specified group.\n",
            "minimum": 0,
            "type": "integer"
          },
          "groupName": {
            "description": "Descriptive label for the group.\n",
            "minLength": 1,
            "type": "string"
          },
          "modifiedBy": {
            "description": "The user who last edited the asset.\n",
            "minLength": 1,
            "type": "string"
          },
          "modifiedDate": {
            "description": "ISO 8601 timestamp indicating when the asset was last updated.\n",
            "format": "date-time",
            "type": "string"
          },
          "propertyId": {
            "description": "Unique identifier for a property or include. This is what [PAPI](https://techdocs.akamai.com/property-mgr/reference/get-properties) refers to as an `assetId`. Note thereâ€™s a discrepancy between how PAPI and Identity and Access Management refer to `propertyId` values. To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
            "minimum": 0,
            "type": "integer"
          },
          "propertyName": {
            "description": "Name of the property [created in PAPI](https://techdocs.akamai.com/property-mgr/reference/post-properties), or the `includeName` when [creating an include](https://techdocs.akamai.com/property-mgr/reference/post-includes). To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "createdDate",
          "createdBy",
          "modifiedDate",
          "modifiedBy",
          "groupName",
          "groupId",
          "arlConfigFile",
          "propertyId",
          "propertyName"
        ],
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/property-response.yaml"
        }
      },
      "move-property-request": {
        "additionalProperties": false,
        "description": "Describes the request body for moving a property under another group.\n",
        "properties": {
          "destinationGroupId": {
            "description": "Identifies the group where you want to move the `sourceGroupId` within the same parent hierarchy. To get this value, run the [List groups](ref:get-groups) operation.\n",
            "minimum": 0,
            "type": "integer"
          },
          "sourceGroupId": {
            "description": "Identifies the group from which you want to move the asset. To get this value, run the [List properties or includes](ref:get-properties) operation.\n",
            "minimum": 0,
            "type": "integer"
          }
        },
        "required": [
          "sourceGroupId",
          "destinationGroupId"
        ],
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/move-property-request.yaml"
        }
      },
      "resource-item": {
        "additionalProperties": false,
        "description": "Encapsulates information about resources.\n",
        "properties": {
          "modifiedDate": {
            "description": "ISO 8601 timestamp indicating when the resource was last updated.\n",
            "format": "date-time",
            "type": "string"
          },
          "resourceId": {
            "description": "Unique identifier for each resource.\n",
            "minimum": 0,
            "type": "integer"
          },
          "resourceName": {
            "description": "Descriptive label for the resource.\n",
            "minLength": 1,
            "type": "string"
          },
          "resourceType": {
            "description": "Helps to characterize a asset's resource, either `cname`, `arlfile`, `cpcode`, `storagegroup`, `fpdomain`, or `edns`. For more information, see [View property details](https://techdocs.akamai.com/iam/docs/mng-properties).\n",
            "enum": [
              "enable",
              "arlfile",
              "cpcode",
              "storagegroup",
              "fpdomain",
              "edns"
            ],
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "resourceId",
          "resourceType",
          "resourceName",
          "modifiedDate"
        ],
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/resource-item.yaml"
        }
      },
      "list-of-resource-item": {
        "description": "Encapsulates information about resources.\n",
        "items": {
          "additionalProperties": false,
          "description": "Encapsulates information about resources.\n",
          "properties": {
            "modifiedDate": {
              "description": "ISO 8601 timestamp indicating when the resource was last updated.\n",
              "format": "date-time",
              "type": "string"
            },
            "resourceId": {
              "description": "Unique identifier for each resource.\n",
              "minimum": 0,
              "type": "integer"
            },
            "resourceName": {
              "description": "Descriptive label for the resource.\n",
              "minLength": 1,
              "type": "string"
            },
            "resourceType": {
              "description": "Helps to characterize a asset's resource, either `cname`, `arlfile`, `cpcode`, `storagegroup`, `fpdomain`, or `edns`. For more information, see [View property details](https://techdocs.akamai.com/iam/docs/mng-properties).\n",
              "enum": [
                "enable",
                "arlfile",
                "cpcode",
                "storagegroup",
                "fpdomain",
                "edns"
              ],
              "minLength": 1,
              "type": "string"
            }
          },
          "required": [
            "resourceId",
            "resourceType",
            "resourceName",
            "modifiedDate"
          ],
          "type": "object",
          "x-akamai": {
            "file-path": "schemas/resource-item.yaml"
          }
        },
        "minItems": 0,
        "type": "array",
        "x-akamai": {
          "file-path": "schemas/list-of-resource-item.yaml"
        }
      },
      "user-property-id": {
        "additionalProperties": false,
        "description": "Encapsulates all the users of a property by property ID.\n",
        "properties": {
          "firstName": {
            "description": "The user's first name.\n",
            "minLength": 1,
            "type": "string"
          },
          "isBlocked": {
            "description": "Whether a user's access to an asset is blocked.\n",
            "type": "boolean"
          },
          "lastName": {
            "description": "The user's surname.\n",
            "minLength": 1,
            "type": "string"
          },
          "uiIdentityId": {
            "description": "Unique identifier for each user, which corresponds to their Control Center profile or client ID. Also known as a `contactId` in other APIs.\n",
            "minLength": 1,
            "type": "string"
          },
          "uiUserName": {
            "description": "The user's username in Control Center.\n",
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "uiUserName",
          "uiIdentityId",
          "firstName",
          "lastName",
          "isBlocked"
        ],
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/user-property-id.yaml"
        }
      },
      "users-of-property-response": {
        "description": "Encapsulates all the users of a property by property ID.\n",
        "items": {
          "additionalProperties": false,
          "description": "Encapsulates all the users of a property by property ID.\n",
          "properties": {
            "firstName": {
              "description": "The user's first name.\n",
              "minLength": 1,
              "type": "string"
            },
            "isBlocked": {
              "description": "Whether a user's access to an asset is blocked.\n",
              "type": "boolean"
            },
            "lastName": {
              "description": "The user's surname.\n",
              "minLength": 1,
              "type": "string"
            },
            "uiIdentityId": {
              "description": "Unique identifier for each user, which corresponds to their Control Center profile or client ID. Also known as a `contactId` in other APIs.\n",
              "minLength": 1,
              "type": "string"
            },
            "uiUserName": {
              "description": "The user's username in Control Center.\n",
              "minLength": 1,
              "type": "string"
            }
          },
          "required": [
            "uiUserName",
            "uiIdentityId",
            "firstName",
            "lastName",
            "isBlocked"
          ],
          "type": "object",
          "x-akamai": {
            "file-path": "schemas/user-property-id.yaml"
          }
        },
        "minItems": 0,
        "type": "array",
        "x-akamai": {
          "file-path": "schemas/users-of-property-response.yaml"
        }
      },
      "user-block-uiidentities": {
        "additionalProperties": false,
        "description": "Encapsulates all the users who needs to be blocked based on UI identities.\n",
        "properties": {
          "uiIdentityId": {
            "description": "Unique identifier for each user, which corresponds to their Control Center profile or client ID. Also known as a `contactId` in other APIs. To get this value, run the [List users for property or include](ref:get-property-users) operation.\n",
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "uiIdentityId"
        ],
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/user-block-uiidentities.yaml"
        }
      },
      "users-block-uiidentities": {
        "description": "Encapsulates all the users who needs to be blocked based on UI identities.\n",
        "items": {
          "additionalProperties": false,
          "description": "Encapsulates all the users who needs to be blocked based on UI identities.\n",
          "properties": {
            "uiIdentityId": {
              "description": "Unique identifier for each user, which corresponds to their Control Center profile or client ID. Also known as a `contactId` in other APIs. To get this value, run the [List users for property or include](ref:get-property-users) operation.\n",
              "minLength": 1,
              "type": "string"
            }
          },
          "required": [
            "uiIdentityId"
          ],
          "type": "object",
          "x-akamai": {
            "file-path": "schemas/user-block-uiidentities.yaml"
          }
        },
        "minItems": 0,
        "type": "array",
        "x-akamai": {
          "file-path": "schemas/users-block-uiidentities.yaml"
        }
      }
    }
  },
  "x-akamai": {
    "auth-type": "EDGE_GRID",
    "file-path": "02-properties-api.yaml"
  }
}