{
  "openapi": "3.0.0",
  "info": {
    "title": "Properties",
    "version": "3"
  },
  "servers": [
    {
      "url": "https://{hostname}/identity-management/v3"
    }
  ],
  "tags": [
    {
      "description": "Fetch properties and includes used by an account with their details,\nincluding their users.\n",
      "name": "Assets"
    },
    {
      "description": "Fetch resources used by a property or include.\n",
      "name": "Resources"
    }
  ],
  "paths": {
    "/user-admin/properties": {
      "x-akamai": {
        "path-info": "/user-admin/properties"
      },
      "get": {
        "operationId": "get-properties",
        "summary": "List properties or includes",
        "tags": [
          "Assets"
        ],
        "description": "This operation lists the properties and includes for the current account or other managed accounts using the `accountSwitchKey` parameter. Include the `groupId` parameter in your request to filter the results by group. The response returns a list of `propertyId` regardless of whether they represent a property or include in PAPI. To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
        "parameters": [
          {
            "name": "groupId",
            "in": "query",
            "description": "Unique identifier for each group. To get this value, run the [List groups](ref:get-groups) operation.\n",
            "schema": {
              "type": "integer",
              "example": 54321
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The response provides the assets.\n",
            "content": {
              "application/json": {
                "example": [
                  {
                    "groupName": "Internet Company",
                    "groupId": 32145,
                    "propertyId": 99999999,
                    "propertyTypeDescription": "On Demand Media",
                    "propertyName": "0rb-internet-company-01.com",
                    "actions": {
                      "move": true
                    }
                  },
                  {
                    "groupName": "Digital Company",
                    "groupId": 12345,
                    "propertyId": 88888888,
                    "propertyTypeDescription": "On Demand Media",
                    "propertyName": "0rb-digital-company-01.com",
                    "actions": {
                      "move": true
                    }
                  }
                ],
                "schema": {
                  "type": "array",
                  "description": "Encapsulates information about a property.\n",
                  "items": {
                    "type": "object",
                    "description": "Encapsulates information about a property.\n",
                    "additionalProperties": false,
                    "required": [
                      "propertyId",
                      "groupId",
                      "groupName",
                      "propertyName",
                      "propertyTypeDescription",
                      "actions"
                    ],
                    "properties": {
                      "propertyId": {
                        "type": "integer",
                        "description": "A unique identifier for each property.\n"
                      },
                      "propertyName": {
                        "type": "string",
                        "description": "The name for a property.\n"
                      },
                      "propertyTypeDescription": {
                        "type": "string",
                        "description": "Identifies the product-type such as `On Demand Media`, `Site`, `Application`, `Live Media Streams`, or `NetStorage`.\n"
                      },
                      "groupId": {
                        "type": "integer",
                        "description": "A unique identifier for each group.\n"
                      },
                      "groupName": {
                        "type": "string",
                        "description": "A group's name.\n"
                      },
                      "actions": {
                        "type": "object",
                        "description": "Encapsulates permissions available to the user for this group. This data is available when you specify the `actions` parameter of the same name, not to be confused with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
                        "additionalProperties": false,
                        "properties": {
                          "move": {
                            "type": "boolean",
                            "description": "Move a property from one group to another group.\n"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user-admin/properties/{assetId}": {
      "x-akamai": {
        "path-info": "/user-admin/properties/{assetId}"
      },
      "parameters": [
        {
          "name": "assetId",
          "in": "path",
          "description": "Unique identifier for each asset, either a property or an include. To get this value, run the [List properties or includes](ref:get-properties) operation.\n",
          "required": true,
          "schema": {
            "type": "integer",
            "example": 9678999
          }
        }
      ],
      "get": {
        "operationId": "get-property",
        "summary": "Get a property or include",
        "tags": [
          "Assets"
        ],
        "description": "This operation fetches a property's or include's details. The response returns details for `propertyId` regardless of whether it represent a property or include in PAPI. To learn more, see [Manage access to properties and includes](ref:manage-access-to-properties-and-includes).\n",
        "parameters": [
          {
            "name": "groupId",
            "in": "query",
            "description": "Unique identifier for each group. To get this value, run the [List groups](ref:get-groups) operation.\n",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 32145
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The response provides the asset's details.\n",
            "content": {
              "application/json": {
                "example": {
                  "createdDate": "2017-07-27T18:11:25.000Z",
                  "createdBy": "afero@example.com",
                  "modifiedDate": "2017-07-27T18:11:25.000Z",
                  "modifiedBy": "adevi@example.com",
                  "groupName": "Sales Team",
                  "groupId": 12345,
                  "arlConfigFile": "0rb-internet-company-01.com.xml",
                  "propertyId": 9678999,
                  "propertyName": "0rb-internet-company-01.com"
                },
                "schema": {
                  "type": "object",
                  "description": "Encapsulates information about a property.\n",
                  "additionalProperties": false,
                  "required": [
                    "createdDate",
                    "createdBy",
                    "modifiedDate",
                    "modifiedBy",
                    "groupName",
                    "groupId",
                    "arlConfigFile",
                    "propertyId",
                    "propertyName"
                  ],
                  "properties": {
                    "arlConfigFile": {
                      "type": "string",
                      "description": "The configuration file. The `arlConfigFile` is the same as the `propertyName` with an xml extension.\n"
                    },
                    "createdBy": {
                      "type": "string",
                      "description": "The username of the person who created the property.\n"
                    },
                    "createdDate": {
                      "type": "string",
                      "description": "ISO 8601 timestamp indicating when the property was originally created.\n",
                      "format": "date-time"
                    },
                    "groupId": {
                      "type": "integer",
                      "description": "A unique identifier for each group.\n"
                    },
                    "groupName": {
                      "type": "string",
                      "description": "A group's name.\n"
                    },
                    "modifiedBy": {
                      "type": "string",
                      "description": "The username of the last person to edit the property.\n"
                    },
                    "modifiedDate": {
                      "type": "string",
                      "description": "ISO 8601 timestamp indicating when the property was last updated.\n",
                      "format": "date-time"
                    },
                    "propertyId": {
                      "type": "integer",
                      "description": "A unique identifier for each property.\n"
                    },
                    "propertyName": {
                      "type": "string",
                      "description": "The name for a property.\n"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "operationId": "put-property",
        "summary": "Move a property or include",
        "tags": [
          "Assets"
        ],
        "description": "This operation moves a property or include from one group to another group. You can only move an asset into another group within the same group hierarchy. Depending on your role in the destination group, you may lose access to resources the asset uses. Before moving an asset, run the [List users affected by moving a group](ref:get-move-affected-users) operation to review which users will be affected by the move.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "sourceGroupId": 11111,
                "destinationGroupId": 22222
              },
              "schema": {
                "type": "object",
                "description": "Describes the request body for moving a property under another group.\n",
                "additionalProperties": false,
                "required": [
                  "sourceGroupId",
                  "destinationGroupId"
                ],
                "properties": {
                  "destinationGroupId": {
                    "type": "integer",
                    "description": "Identifies the group within account hierarchy where you want to move the `sourceGroupId`. It can't be a child or descendant of the current group.\n"
                  },
                  "sourceGroupId": {
                    "type": "integer",
                    "description": "Identifies the nested group you want to move to the `destinationGroupId`.\n"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Asset successfully moved.\n"
          }
        }
      }
    },
    "/user-admin/properties/{assetId}/resources": {
      "x-akamai": {
        "path-info": "/user-admin/properties/{assetId}/resources"
      },
      "parameters": [
        {
          "name": "assetId",
          "in": "path",
          "description": "Unique identifier for each asset, either a property or an include. To get this value, run the [List properties or includes](ref:get-properties) operation.\n",
          "required": true,
          "schema": {
            "type": "integer",
            "example": 9678999
          }
        }
      ],
      "get": {
        "operationId": "get-property-resources",
        "summary": "Get asset's resources",
        "tags": [
          "Resources"
        ],
        "description": "This operation lists resources a property or include uses to deliver your web content across Akamai's edge network. You can think of these resources as objects, like CP codes and configuration files. For example, an ARL (Akamai resource locator) configuration file specifies how Akamai purges versions of an object that you can’t purge using just the URL.\n",
        "parameters": [
          {
            "name": "groupId",
            "in": "query",
            "description": "Unique identifier for each group. To get this value, run the [List groups](ref:get-groups) operation.\n",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 32145
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The response provides the resources.\n",
            "content": {
              "application/json": {
                "example": [
                  {
                    "resourceId": 111111,
                    "resourceType": "arlfile",
                    "resourceName": "0rb-internet-company-01.com.xml",
                    "modifiedDate": "2017-09-07T17:00:58.000Z"
                  },
                  {
                    "resourceId": 8988898,
                    "resourceType": "cpcode",
                    "resourceName": "mycpcode(123456)",
                    "modifiedDate": "2017-04-24T16:19:27.000Z"
                  }
                ],
                "schema": {
                  "type": "array",
                  "description": "Encapsulates information about resources.\n",
                  "items": {
                    "type": "object",
                    "description": "Encapsulates information about resources.\n",
                    "additionalProperties": false,
                    "properties": {
                      "resourceId": {
                        "type": "integer",
                        "description": "Unique identifier for each resource.\n"
                      },
                      "resourceType": {
                        "type": "string",
                        "description": "The type of the resource, either `cname`, `arlfile`, `cpcode`, `storagegroup`, `fpdomain`, or `edns`.\n",
                        "enum": [
                          "cname",
                          "arlfile",
                          "cpcode",
                          "storagegroup",
                          "fpdomain",
                          "edns"
                        ]
                      },
                      "resourceName": {
                        "type": "string",
                        "description": "The name you supply for the resource.\n"
                      },
                      "modifiedDate": {
                        "type": "string",
                        "description": "ISO 8601 timestamp indicating when the resource was last updated.\n",
                        "format": "date-time"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user-admin/properties/{assetId}/users": {
      "x-akamai": {
        "path-info": "/user-admin/properties/{assetId}/users"
      },
      "parameters": [
        {
          "name": "assetId",
          "in": "path",
          "description": "Unique identifier for each asset, either a property or an include. To get this value, run the [List properties or includes](ref:get-properties) operation.\n",
          "required": true,
          "schema": {
            "type": "integer",
            "example": 9678999
          }
        }
      ],
      "get": {
        "operationId": "get-property-users",
        "summary": "List users for property or include",
        "tags": [
          "Assets"
        ],
        "description": "This operation lists users who can access a property or include.\n",
        "parameters": [
          {
            "name": "userType",
            "in": "query",
            "description": "Filters the list by users who have `lostAccess` or the reverse `gainAccess`.\n",
            "schema": {
              "type": "string",
              "example": "lostAccess",
              "enum": [
                "lostAccess",
                "gainAccess"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The response provides the users accessing the property or include.\n",
            "content": {
              "application/json": {
                "example": [
                  {
                    "uiUserName": "szhang",
                    "uiIdentityId": "B-3-146FAB9",
                    "firstName": "Media",
                    "lastName": "QA",
                    "isBlocked": true
                  },
                  {
                    "uiUserName": "mrossi",
                    "uiIdentityId": "B-C-IP9IND",
                    "firstName": "Bert",
                    "lastName": "Moody",
                    "isBlocked": false
                  }
                ],
                "schema": {
                  "type": "array",
                  "description": "All the users of a property, by property ID.\n",
                  "items": {
                    "type": "object",
                    "description": "This object encapsulates all the users of a property by property ID.\n",
                    "additionalProperties": false,
                    "required": [
                      "uiUserName",
                      "uiIdentityId",
                      "firstName",
                      "lastName",
                      "isBlocked"
                    ],
                    "properties": {
                      "uiUserName": {
                        "type": "string",
                        "description": "The full name for the user, as it appears in interfaces.\n"
                      },
                      "uiIdentityId": {
                        "type": "string",
                        "description": "A unique identifier for a user. Also known as a `contactId` in other APIs.\n"
                      },
                      "firstName": {
                        "type": "string",
                        "description": "The user's first name.\n"
                      },
                      "lastName": {
                        "type": "string",
                        "description": "The user's last name.\n"
                      },
                      "isBlocked": {
                        "type": "boolean",
                        "description": "Shows if the user is blocked.\n"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user-admin/properties/{assetId}/users/block": {
      "x-akamai": {
        "path-info": "/user-admin/properties/{assetId}/users/block"
      },
      "parameters": [
        {
          "name": "assetId",
          "in": "path",
          "description": "Unique identifier for each asset, either a property or an include. To get this value, run the [List properties or includes](ref:get-properties) operation.\n",
          "required": true,
          "schema": {
            "type": "integer",
            "example": 9678999
          }
        }
      ],
      "put": {
        "operationId": "put-property-users-block",
        "summary": "Block users from a property or include",
        "tags": [
          "Assets"
        ],
        "description": "This operation blocks the users on a property or include.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": [
                {
                  "uiIdentityId": "B-3-146FAB9"
                },
                {
                  "uiIdentityId": "B-C-IP9IND"
                }
              ],
              "schema": {
                "type": "array",
                "description": "Encapsulates all the users who needs to be blocked based on UI identities.\n",
                "minItems": 0,
                "items": {
                  "type": "object",
                  "description": "Encapsulates all the users who needs to be blocked based on UI identities.\n",
                  "additionalProperties": false,
                  "required": [
                    "uiIdentityId"
                  ],
                  "properties": {
                    "uiIdentityId": {
                      "type": "string",
                      "description": "Unique identifier for each user, which corresponds to their Control Center profile or client ID. Also known as a `contactId` in other APIs. To get this value, run the [List users for property or include](ref:get-property-users) operation.\n",
                      "minLength": 1
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The response provides the users blocked from the asset.\n",
            "content": {
              "application/json": {
                "example": [
                  {
                    "uiUserName": "szhang",
                    "uiIdentityId": "B-3-146FAB9",
                    "firstName": "Media",
                    "lastName": "QA",
                    "isBlocked": true
                  },
                  {
                    "uiUserName": "mrossi",
                    "uiIdentityId": "B-C-IP9IND",
                    "firstName": "Bert",
                    "lastName": "Moody",
                    "isBlocked": false
                  }
                ],
                "schema": {
                  "type": "array",
                  "description": "All the users of a property, by property ID.\n",
                  "items": {
                    "type": "object",
                    "description": "This object encapsulates all the users of a property by property ID.\n",
                    "additionalProperties": false,
                    "required": [
                      "uiUserName",
                      "uiIdentityId",
                      "firstName",
                      "lastName",
                      "isBlocked"
                    ],
                    "properties": {
                      "uiUserName": {
                        "type": "string",
                        "description": "The full name for the user, as it appears in interfaces.\n"
                      },
                      "uiIdentityId": {
                        "type": "string",
                        "description": "A unique identifier for a user. Also known as a `contactId` in other APIs.\n"
                      },
                      "firstName": {
                        "type": "string",
                        "description": "The user's first name.\n"
                      },
                      "lastName": {
                        "type": "string",
                        "description": "The user's last name.\n"
                      },
                      "isBlocked": {
                        "type": "boolean",
                        "description": "Shows if the user is blocked.\n"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "group-id-opt-group-id": {
        "name": "groupId",
        "in": "query",
        "description": "Unique identifier for each group. To get this value, run the [List groups](ref:get-groups) operation.\n",
        "schema": {
          "type": "integer",
          "example": 54321
        }
      },
      "asset-id-path": {
        "name": "assetId",
        "in": "path",
        "description": "Unique identifier for each asset, either a property or an include. To get this value, run the [List properties or includes](ref:get-properties) operation.\n",
        "required": true,
        "schema": {
          "type": "integer",
          "example": 9678999
        }
      },
      "group-id-req-qp-group-id": {
        "name": "groupId",
        "in": "query",
        "description": "Unique identifier for each group. To get this value, run the [List groups](ref:get-groups) operation.\n",
        "required": true,
        "schema": {
          "type": "integer",
          "example": 32145
        }
      },
      "user-type-query": {
        "name": "userType",
        "in": "query",
        "description": "Filters the list by users who have `lostAccess` or the reverse `gainAccess`.\n",
        "schema": {
          "type": "string",
          "example": "lostAccess",
          "enum": [
            "lostAccess",
            "gainAccess"
          ]
        }
      }
    },
    "schemas": {
      "property-list-item": {
        "type": "object",
        "description": "Encapsulates information about a property.\n",
        "additionalProperties": false,
        "required": [
          "propertyId",
          "groupId",
          "groupName",
          "propertyName",
          "propertyTypeDescription",
          "actions"
        ],
        "properties": {
          "propertyId": {
            "type": "integer",
            "description": "A unique identifier for each property.\n"
          },
          "propertyName": {
            "type": "string",
            "description": "The name for a property.\n"
          },
          "propertyTypeDescription": {
            "type": "string",
            "description": "Identifies the product-type such as `On Demand Media`, `Site`, `Application`, `Live Media Streams`, or `NetStorage`.\n"
          },
          "groupId": {
            "type": "integer",
            "description": "A unique identifier for each group.\n"
          },
          "groupName": {
            "type": "string",
            "description": "A group's name.\n"
          },
          "actions": {
            "type": "object",
            "description": "Encapsulates permissions available to the user for this group. This data is available when you specify the `actions` parameter of the same name, not to be confused with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
            "additionalProperties": false,
            "properties": {
              "move": {
                "type": "boolean",
                "description": "Move a property from one group to another group.\n"
              }
            }
          }
        }
      },
      "list-of-property-list-item": {
        "type": "array",
        "description": "Encapsulates information about a property.\n",
        "items": {
          "type": "object",
          "description": "Encapsulates information about a property.\n",
          "additionalProperties": false,
          "required": [
            "propertyId",
            "groupId",
            "groupName",
            "propertyName",
            "propertyTypeDescription",
            "actions"
          ],
          "properties": {
            "propertyId": {
              "type": "integer",
              "description": "A unique identifier for each property.\n"
            },
            "propertyName": {
              "type": "string",
              "description": "The name for a property.\n"
            },
            "propertyTypeDescription": {
              "type": "string",
              "description": "Identifies the product-type such as `On Demand Media`, `Site`, `Application`, `Live Media Streams`, or `NetStorage`.\n"
            },
            "groupId": {
              "type": "integer",
              "description": "A unique identifier for each group.\n"
            },
            "groupName": {
              "type": "string",
              "description": "A group's name.\n"
            },
            "actions": {
              "type": "object",
              "description": "Encapsulates permissions available to the user for this group. This data is available when you specify the `actions` parameter of the same name, not to be confused with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
              "additionalProperties": false,
              "properties": {
                "move": {
                  "type": "boolean",
                  "description": "Move a property from one group to another group.\n"
                }
              }
            }
          }
        }
      },
      "property-response": {
        "type": "object",
        "description": "Encapsulates information about a property.\n",
        "additionalProperties": false,
        "required": [
          "createdDate",
          "createdBy",
          "modifiedDate",
          "modifiedBy",
          "groupName",
          "groupId",
          "arlConfigFile",
          "propertyId",
          "propertyName"
        ],
        "properties": {
          "arlConfigFile": {
            "type": "string",
            "description": "The configuration file. The `arlConfigFile` is the same as the `propertyName` with an xml extension.\n"
          },
          "createdBy": {
            "type": "string",
            "description": "The username of the person who created the property.\n"
          },
          "createdDate": {
            "type": "string",
            "description": "ISO 8601 timestamp indicating when the property was originally created.\n",
            "format": "date-time"
          },
          "groupId": {
            "type": "integer",
            "description": "A unique identifier for each group.\n"
          },
          "groupName": {
            "type": "string",
            "description": "A group's name.\n"
          },
          "modifiedBy": {
            "type": "string",
            "description": "The username of the last person to edit the property.\n"
          },
          "modifiedDate": {
            "type": "string",
            "description": "ISO 8601 timestamp indicating when the property was last updated.\n",
            "format": "date-time"
          },
          "propertyId": {
            "type": "integer",
            "description": "A unique identifier for each property.\n"
          },
          "propertyName": {
            "type": "string",
            "description": "The name for a property.\n"
          }
        }
      },
      "move-property-request": {
        "type": "object",
        "description": "Describes the request body for moving a property under another group.\n",
        "additionalProperties": false,
        "required": [
          "sourceGroupId",
          "destinationGroupId"
        ],
        "properties": {
          "destinationGroupId": {
            "type": "integer",
            "description": "Identifies the group within account hierarchy where you want to move the `sourceGroupId`. It can't be a child or descendant of the current group.\n"
          },
          "sourceGroupId": {
            "type": "integer",
            "description": "Identifies the nested group you want to move to the `destinationGroupId`.\n"
          }
        }
      },
      "resource-item": {
        "type": "object",
        "description": "Encapsulates information about resources.\n",
        "additionalProperties": false,
        "properties": {
          "resourceId": {
            "type": "integer",
            "description": "Unique identifier for each resource.\n"
          },
          "resourceType": {
            "type": "string",
            "description": "The type of the resource, either `cname`, `arlfile`, `cpcode`, `storagegroup`, `fpdomain`, or `edns`.\n",
            "enum": [
              "cname",
              "arlfile",
              "cpcode",
              "storagegroup",
              "fpdomain",
              "edns"
            ]
          },
          "resourceName": {
            "type": "string",
            "description": "The name you supply for the resource.\n"
          },
          "modifiedDate": {
            "type": "string",
            "description": "ISO 8601 timestamp indicating when the resource was last updated.\n",
            "format": "date-time"
          }
        }
      },
      "list-of-resource-item": {
        "type": "array",
        "description": "Encapsulates information about resources.\n",
        "items": {
          "type": "object",
          "description": "Encapsulates information about resources.\n",
          "additionalProperties": false,
          "properties": {
            "resourceId": {
              "type": "integer",
              "description": "Unique identifier for each resource.\n"
            },
            "resourceType": {
              "type": "string",
              "description": "The type of the resource, either `cname`, `arlfile`, `cpcode`, `storagegroup`, `fpdomain`, or `edns`.\n",
              "enum": [
                "cname",
                "arlfile",
                "cpcode",
                "storagegroup",
                "fpdomain",
                "edns"
              ]
            },
            "resourceName": {
              "type": "string",
              "description": "The name you supply for the resource.\n"
            },
            "modifiedDate": {
              "type": "string",
              "description": "ISO 8601 timestamp indicating when the resource was last updated.\n",
              "format": "date-time"
            }
          }
        }
      },
      "user-property-id": {
        "type": "object",
        "description": "This object encapsulates all the users of a property by property ID.\n",
        "additionalProperties": false,
        "required": [
          "uiUserName",
          "uiIdentityId",
          "firstName",
          "lastName",
          "isBlocked"
        ],
        "properties": {
          "uiUserName": {
            "type": "string",
            "description": "The full name for the user, as it appears in interfaces.\n"
          },
          "uiIdentityId": {
            "type": "string",
            "description": "A unique identifier for a user. Also known as a `contactId` in other APIs.\n"
          },
          "firstName": {
            "type": "string",
            "description": "The user's first name.\n"
          },
          "lastName": {
            "type": "string",
            "description": "The user's last name.\n"
          },
          "isBlocked": {
            "type": "boolean",
            "description": "Shows if the user is blocked.\n"
          }
        }
      },
      "users-of-property-response": {
        "type": "array",
        "description": "All the users of a property, by property ID.\n",
        "items": {
          "type": "object",
          "description": "This object encapsulates all the users of a property by property ID.\n",
          "additionalProperties": false,
          "required": [
            "uiUserName",
            "uiIdentityId",
            "firstName",
            "lastName",
            "isBlocked"
          ],
          "properties": {
            "uiUserName": {
              "type": "string",
              "description": "The full name for the user, as it appears in interfaces.\n"
            },
            "uiIdentityId": {
              "type": "string",
              "description": "A unique identifier for a user. Also known as a `contactId` in other APIs.\n"
            },
            "firstName": {
              "type": "string",
              "description": "The user's first name.\n"
            },
            "lastName": {
              "type": "string",
              "description": "The user's last name.\n"
            },
            "isBlocked": {
              "type": "boolean",
              "description": "Shows if the user is blocked.\n"
            }
          }
        }
      },
      "user-block-uiidentities": {
        "type": "object",
        "description": "Encapsulates all the users who needs to be blocked based on UI identities.\n",
        "additionalProperties": false,
        "required": [
          "uiIdentityId"
        ],
        "properties": {
          "uiIdentityId": {
            "type": "string",
            "description": "Unique identifier for each user, which corresponds to their Control Center profile or client ID. Also known as a `contactId` in other APIs. To get this value, run the [List users for property or include](ref:get-property-users) operation.\n",
            "minLength": 1
          }
        }
      },
      "users-block-uiidentities": {
        "type": "array",
        "description": "Encapsulates all the users who needs to be blocked based on UI identities.\n",
        "minItems": 0,
        "items": {
          "type": "object",
          "description": "Encapsulates all the users who needs to be blocked based on UI identities.\n",
          "additionalProperties": false,
          "required": [
            "uiIdentityId"
          ],
          "properties": {
            "uiIdentityId": {
              "type": "string",
              "description": "Unique identifier for each user, which corresponds to their Control Center profile or client ID. Also known as a `contactId` in other APIs. To get this value, run the [List users for property or include](ref:get-property-users) operation.\n",
              "minLength": 1
            }
          }
        }
      }
    }
  },
  "x-akamai": {
    "auth-type": "EDGE_GRID"
  }
}