{
  "openapi": "3.0.0",
  "info": {
    "title": "IP access control lists",
    "version": "3",
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "servers": [
    {
      "url": "https://{hostname}/identity-management/v3"
    }
  ],
  "tags": [
    {
      "description": "Manage the CIDR blocks in your account's allowlist.\n",
      "name": "CIDR blocks"
    },
    {
      "description": "Manage the IP allowlist for an account.\n",
      "name": "IP allowlists"
    }
  ],
  "paths": {
    "/user-admin/ip-acl/allowlist": {
      "x-akamai": {
        "file-path": "paths/cidr-blocks.yaml",
        "path-info": "/user-admin/ip-acl/allowlist"
      },
      "post": {
        "operationId": "post-allowlist",
        "summary": "Create a CIDR block",
        "tags": [
          "CIDR blocks"
        ],
        "description": "This operation adds CIDR blocks to your account's allowlist. You can add only one CIDR block at a time. Before creating the CIDR block, you may want to [validate it](ref:get-allowlist-validate), to check if its format is correct.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "enabled": true,
                "comments": "EMEA Offices",
                "cidrBlock": "128.10.46.60/24"
              },
              "schema": {
                "additionalProperties": false,
                "description": "Encapsulates all data sent while creating or updating a CIDR block.",
                "properties": {
                  "cidrBlock": {
                    "description": "The value of an IP address or IP address range.\n",
                    "minLength": 1,
                    "type": "string"
                  },
                  "comments": {
                    "description": "Descriptive label you provide for the CIDR block.\n",
                    "minLength": 1,
                    "type": "string"
                  },
                  "enabled": {
                    "description": "Enables the IP allowlist on the account.\n",
                    "type": "boolean"
                  }
                },
                "required": [
                  "enabled",
                  "cidrBlock"
                ],
                "type": "object",
                "x-akamai": {
                  "file-path": "schemas/post-ip-acl.yaml"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "CIDR block successfully created.\n",
            "headers": {
              "Location": {
                "description": "A URL path to the newly created object.",
                "schema": {
                  "type": "string"
                },
                "x-akamai": {
                  "file-path": "headers/location.yaml"
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "cidrBlockId": 2567,
                  "enabled": true,
                  "comments": "APAC Region",
                  "cidrBlock": "128.5.6.6/24",
                  "createdDate": "2017-07-27T18:11:25.000Z",
                  "createdBy": "alfulani",
                  "modifiedDate": "2017-07-27T18:11:25.000Z",
                  "modifiedBy": "alfulani",
                  "actions": {
                    "delete": true,
                    "edit": false
                  }
                },
                "schema": {
                  "additionalProperties": false,
                  "description": "Encapsulates all members for a CIDR block in the IP allowlist data structure.",
                  "properties": {
                    "actions": {
                      "additionalProperties": false,
                      "description": "Specifies activities available for the CIDR block.\n",
                      "properties": {
                        "delete": {
                          "description": "Whether you can delete this CIDR block. You can't delete a CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                          "type": "boolean"
                        },
                        "edit": {
                          "description": "Whether you can edit this CIDR block. You can't edit  CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                          "type": "boolean"
                        }
                      },
                      "required": [
                        "delete",
                        "edit"
                      ],
                      "type": "object"
                    },
                    "cidrBlock": {
                      "description": "The value of an IP address or IP address range.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "cidrBlockId": {
                      "description": "Unique identifier for each CIDR block.\n",
                      "minimum": 0,
                      "type": "integer"
                    },
                    "comments": {
                      "description": "Descriptive label you provide for the CIDR block.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "createdBy": {
                      "description": "The user who created the CIDR block.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "createdDate": {
                      "description": "ISO 8601 timestamp indicating when the CIDR block was created.\n",
                      "format": "date-time",
                      "type": "string"
                    },
                    "enabled": {
                      "description": "Whether the IP allowlist is enabled on the account.\n",
                      "type": "boolean"
                    },
                    "modifiedBy": {
                      "description": "The user who last edited the CIDR block.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "modifiedDate": {
                      "description": "ISO 8601 timestamp indicating when the CIDR block was last modified.\n",
                      "format": "date-time",
                      "type": "string"
                    }
                  },
                  "required": [
                    "cidrBlockId",
                    "enabled",
                    "cidrBlock",
                    "createdDate",
                    "createdBy",
                    "modifiedDate",
                    "modifiedBy"
                  ],
                  "type": "object",
                  "x-akamai": {
                    "file-path": "schemas/ip-acl-200.yaml"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "operationId": "get-allowlist",
        "summary": "List CIDR blocks",
        "tags": [
          "CIDR blocks"
        ],
        "description": "This operation lists all CIDR blocks on your current account's allowlist or other managed accounts using the `accountSwitchKey` parameter. Your API client designates the allowlist for the account.\n",
        "parameters": [
          {
            "description": "Includes actions you can perform on the object, `false` by default.",
            "in": "query",
            "name": "actions",
            "schema": {
              "default": false,
              "example": true,
              "type": "boolean"
            },
            "x-akamai": {
              "file-path": "parameters/actions-query.yaml"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The response provides the CIDR blocks.\n",
            "content": {
              "application/json": {
                "example": [
                  {
                    "cidrBlockId": 921,
                    "enabled": true,
                    "comments": "West Coast Office",
                    "cidrBlock": "127.0.0.1/24",
                    "createdDate": "2017-07-27T18:11:25.000Z",
                    "createdBy": "alfulani",
                    "modifiedDate": "2017-07-27T18:11:25.000Z",
                    "modifiedBy": "szhang",
                    "actions": {
                      "delete": true,
                      "edit": true
                    }
                  },
                  {
                    "cidrBlockId": 6042,
                    "enabled": true,
                    "comments": "East Coast Office",
                    "cidrBlock": "128.5.6.6/24",
                    "createdDate": "2017-07-27T18:11:25.000Z",
                    "createdBy": "mrossi",
                    "modifiedDate": "2017-07-27T18:11:25.000Z",
                    "modifiedBy": "jperez",
                    "actions": {
                      "delete": true,
                      "edit": false
                    }
                  }
                ],
                "schema": {
                  "description": "This object encapsulates a collection of CIDR blocks.",
                  "items": {
                    "additionalProperties": false,
                    "properties": {
                      "actions": {
                        "additionalProperties": false,
                        "description": "Specifies activities available for the CIDR block.\n",
                        "properties": {
                          "delete": {
                            "description": "Whether you can delete this CIDR block. You can't delete a CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                            "type": "boolean"
                          },
                          "edit": {
                            "description": "Whether you can edit this CIDR block. You can't edit  CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                            "type": "boolean"
                          }
                        },
                        "required": [
                          "delete",
                          "edit"
                        ],
                        "type": "object"
                      },
                      "cidrBlock": {
                        "description": "The value of an IP address or IP address range.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "cidrBlockId": {
                        "description": "Unique identifier for each CIDR block.\n",
                        "minimum": 0,
                        "type": "integer"
                      },
                      "comments": {
                        "description": "Descriptive label you provide for the CIDR block.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "createdBy": {
                        "description": "The user who created the CIDR block.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "createdDate": {
                        "description": "ISO 8601 timestamp indicating when the CIDR block was created.\n",
                        "format": "date-time",
                        "type": "string"
                      },
                      "enabled": {
                        "description": "Whether the CIDR block is enabled.\n",
                        "type": "boolean"
                      },
                      "modifiedBy": {
                        "description": "The user who last edited the CIDR block.\n",
                        "minLength": 1,
                        "type": "string"
                      },
                      "modifiedDate": {
                        "description": "ISO 8601 timestamp indicating when the CIDR block was last modified.\n",
                        "format": "date-time",
                        "type": "string"
                      }
                    },
                    "required": [
                      "cidrBlock",
                      "cidrBlockId",
                      "comments",
                      "createdBy",
                      "createdDate",
                      "enabled",
                      "modifiedBy",
                      "modifiedDate"
                    ],
                    "type": "object"
                  },
                  "minItems": 0,
                  "type": "array",
                  "x-akamai": {
                    "file-path": "schemas/ip-acls-200.yaml"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user-admin/ip-acl/allowlist/disable": {
      "post": {
        "description": "This operation disables IP allowlist on your account. After you disable IP allowlist, users can access Control Center regardless of their IP address or who assigns it.\n",
        "operationId": "post-allowlist-disable",
        "responses": {
          "204": {
            "description": "IP allowlist successfully disabled.\n"
          }
        },
        "summary": "Disable IP allowlist",
        "tags": [
          "IP allowlists"
        ]
      },
      "x-akamai": {
        "file-path": "paths/disable.yaml",
        "path-info": "/user-admin/ip-acl/allowlist/disable"
      }
    },
    "/user-admin/ip-acl/allowlist/enable": {
      "x-akamai": {
        "file-path": "paths/enable.yaml",
        "path-info": "/user-admin/ip-acl/allowlist/enable"
      },
      "post": {
        "operationId": "post-allowlist-enable",
        "summary": "Enable IP allowlist",
        "tags": [
          "IP allowlists"
        ],
        "description": "This operation enables IP allowlist on your account. Before you enable IP allowlist, add at least one IP address to allow access to Control Center. The allowlist can't be empty with IP allowlist enabled.\n",
        "responses": {
          "204": {
            "description": "IP allowlist successfully enabled.\n"
          }
        }
      }
    },
    "/user-admin/ip-acl/allowlist/status": {
      "get": {
        "description": "This operation indicates whether IP allowlist is enabled or disabled on your account.\n",
        "operationId": "get-allowlist-status",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "enabled": true
                },
                "schema": {
                  "additionalProperties": false,
                  "description": "Encapsulates the status of IP allowlist on the account.",
                  "properties": {
                    "enabled": {
                      "description": "Whether the IP allowlist is enabled on the account.\n",
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "enabled"
                  ],
                  "type": "object",
                  "x-akamai": {
                    "file-path": "schemas/account-status.yaml"
                  }
                }
              }
            },
            "description": "The response provides IP allowlist status.\n"
          }
        },
        "summary": "View IP allowlist status",
        "tags": [
          "IP allowlists"
        ]
      },
      "x-akamai": {
        "file-path": "paths/status.yaml",
        "path-info": "/user-admin/ip-acl/allowlist/status"
      }
    },
    "/user-admin/ip-acl/allowlist/validate": {
      "get": {
        "description": "This operation checks the format of a potential CIDR block. If it's validated successfully, you can [create it](ref:post-allowlist).\n",
        "operationId": "get-allowlist-validate",
        "parameters": [
          {
            "description": "CIDR block or any IP address value you want to validate. Encode any slash characters as `%2F`. This isn't the same as a `cidrBlockId`.",
            "in": "query",
            "name": "cidrblock",
            "required": true,
            "schema": {
              "example": "127.0.0.1/20",
              "type": "string"
            },
            "x-akamai": {
              "file-path": "parameters/cidr-block-query.yaml"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "CIDR block successfully validated.\n"
          }
        },
        "summary": "Validate CIDR blocks",
        "tags": [
          "CIDR blocks"
        ]
      },
      "x-akamai": {
        "file-path": "paths/validate.yaml",
        "path-info": "/user-admin/ip-acl/allowlist/validate"
      }
    },
    "/user-admin/ip-acl/allowlist/{cidrBlockId}": {
      "x-akamai": {
        "file-path": "paths/cidr-block.yaml",
        "path-info": "/user-admin/ip-acl/allowlist/{cidrBlockId}"
      },
      "parameters": [
        {
          "description": "Unique identifier for each CIDR block. To get this value, run the [List CIDR blocks](ref:get-allowlist) operation.",
          "in": "path",
          "name": "cidrBlockId",
          "required": true,
          "schema": {
            "example": 6688,
            "type": "integer"
          },
          "x-akamai": {
            "file-path": "parameters/cidr-block-id-path.yaml"
          }
        }
      ],
      "get": {
        "operationId": "get-allowlist-cidrblockid",
        "summary": "Get a CIDR block",
        "tags": [
          "CIDR blocks"
        ],
        "description": "This operation retrieves a CIDR block's details.\n",
        "parameters": [
          {
            "description": "Includes actions you can perform on the object, `false` by default.",
            "in": "query",
            "name": "actions",
            "schema": {
              "default": false,
              "example": true,
              "type": "boolean"
            },
            "x-akamai": {
              "file-path": "parameters/actions-query.yaml"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The response provides the CIDR block's details.\n",
            "content": {
              "application/json": {
                "example": {
                  "cidrBlockId": 2567,
                  "enabled": true,
                  "comments": "APAC Region",
                  "cidrBlock": "128.5.6.6/24",
                  "createdDate": "2017-07-27T18:11:25.000Z",
                  "createdBy": "alfulani",
                  "modifiedDate": "2017-07-27T18:11:25.000Z",
                  "modifiedBy": "alfulani",
                  "actions": {
                    "delete": true,
                    "edit": false
                  }
                },
                "schema": {
                  "additionalProperties": false,
                  "description": "Encapsulates all members for a CIDR block in the IP allowlist data structure.",
                  "properties": {
                    "actions": {
                      "additionalProperties": false,
                      "description": "Specifies activities available for the CIDR block.\n",
                      "properties": {
                        "delete": {
                          "description": "Whether you can delete this CIDR block. You can't delete a CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                          "type": "boolean"
                        },
                        "edit": {
                          "description": "Whether you can edit this CIDR block. You can't edit  CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                          "type": "boolean"
                        }
                      },
                      "required": [
                        "delete",
                        "edit"
                      ],
                      "type": "object"
                    },
                    "cidrBlock": {
                      "description": "The value of an IP address or IP address range.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "cidrBlockId": {
                      "description": "Unique identifier for each CIDR block.\n",
                      "minimum": 0,
                      "type": "integer"
                    },
                    "comments": {
                      "description": "Descriptive label you provide for the CIDR block.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "createdBy": {
                      "description": "The user who created the CIDR block.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "createdDate": {
                      "description": "ISO 8601 timestamp indicating when the CIDR block was created.\n",
                      "format": "date-time",
                      "type": "string"
                    },
                    "enabled": {
                      "description": "Whether the IP allowlist is enabled on the account.\n",
                      "type": "boolean"
                    },
                    "modifiedBy": {
                      "description": "The user who last edited the CIDR block.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "modifiedDate": {
                      "description": "ISO 8601 timestamp indicating when the CIDR block was last modified.\n",
                      "format": "date-time",
                      "type": "string"
                    }
                  },
                  "required": [
                    "cidrBlockId",
                    "enabled",
                    "cidrBlock",
                    "createdDate",
                    "createdBy",
                    "modifiedDate",
                    "modifiedBy"
                  ],
                  "type": "object",
                  "x-akamai": {
                    "file-path": "schemas/ip-acl-200.yaml"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "operationId": "put-allowlist-cidrblockid",
        "summary": "Modify a CIDR block",
        "tags": [
          "CIDR blocks"
        ],
        "description": "This operation enables or disables an existing CIDR block, updates comments, IP addresses, or ranges in the CIDR block. Note that you can only update a CIDR block with IP allowlist enabled on the account. There are several CIDR blocks on the allowlist and your attempt to make changes to the CIDR block is from an IP address that's on the allowlist. You can't edit the last CIDR block in the allowlist or the CIDR block allowing access to the current user.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "enabled": true,
                "comments": "EMEA Offices",
                "cidrBlock": "128.10.46.60/24"
              },
              "schema": {
                "additionalProperties": false,
                "description": "Encapsulates all data sent while creating or updating a CIDR block.",
                "properties": {
                  "cidrBlock": {
                    "description": "The value of an IP address or IP address range.\n",
                    "minLength": 1,
                    "type": "string"
                  },
                  "comments": {
                    "description": "Descriptive label you provide for the CIDR block.\n",
                    "minLength": 1,
                    "type": "string"
                  },
                  "enabled": {
                    "description": "Enables the IP allowlist on the account.\n",
                    "type": "boolean"
                  }
                },
                "required": [
                  "enabled",
                  "cidrBlock"
                ],
                "type": "object",
                "x-akamai": {
                  "file-path": "schemas/post-ip-acl.yaml"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The response reflects the modified CIDR block.\n",
            "content": {
              "application/json": {
                "example": {
                  "cidrBlockId": 2567,
                  "enabled": true,
                  "comments": "APAC Region",
                  "cidrBlock": "128.5.6.6/24",
                  "createdDate": "2017-07-27T18:11:25.000Z",
                  "createdBy": "alfulani",
                  "modifiedDate": "2017-07-27T18:11:25.000Z",
                  "modifiedBy": "alfulani",
                  "actions": {
                    "delete": true,
                    "edit": false
                  }
                },
                "schema": {
                  "additionalProperties": false,
                  "description": "Encapsulates all members for a CIDR block in the IP allowlist data structure.",
                  "properties": {
                    "actions": {
                      "additionalProperties": false,
                      "description": "Specifies activities available for the CIDR block.\n",
                      "properties": {
                        "delete": {
                          "description": "Whether you can delete this CIDR block. You can't delete a CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                          "type": "boolean"
                        },
                        "edit": {
                          "description": "Whether you can edit this CIDR block. You can't edit  CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                          "type": "boolean"
                        }
                      },
                      "required": [
                        "delete",
                        "edit"
                      ],
                      "type": "object"
                    },
                    "cidrBlock": {
                      "description": "The value of an IP address or IP address range.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "cidrBlockId": {
                      "description": "Unique identifier for each CIDR block.\n",
                      "minimum": 0,
                      "type": "integer"
                    },
                    "comments": {
                      "description": "Descriptive label you provide for the CIDR block.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "createdBy": {
                      "description": "The user who created the CIDR block.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "createdDate": {
                      "description": "ISO 8601 timestamp indicating when the CIDR block was created.\n",
                      "format": "date-time",
                      "type": "string"
                    },
                    "enabled": {
                      "description": "Whether the IP allowlist is enabled on the account.\n",
                      "type": "boolean"
                    },
                    "modifiedBy": {
                      "description": "The user who last edited the CIDR block.\n",
                      "minLength": 1,
                      "type": "string"
                    },
                    "modifiedDate": {
                      "description": "ISO 8601 timestamp indicating when the CIDR block was last modified.\n",
                      "format": "date-time",
                      "type": "string"
                    }
                  },
                  "required": [
                    "cidrBlockId",
                    "enabled",
                    "cidrBlock",
                    "createdDate",
                    "createdBy",
                    "modifiedDate",
                    "modifiedBy"
                  ],
                  "type": "object",
                  "x-akamai": {
                    "file-path": "schemas/ip-acl-200.yaml"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "operationId": "delete-allowlist-cidrblockid",
        "summary": "Delete a CIDR block",
        "tags": [
          "CIDR blocks"
        ],
        "description": "This operation deletes a CIDR block from the IP allowlist. After you delete a CIDR block, any requests from IP addresses you deleted fail the next time someone tries to log in from that address. Users accessing Control Center from an IP address you delete aren't automatically logged out of Control Center at the time you delete the IP address. With IP allowlist enabled for the account, you can't delete the last CIDR block in the allowlist or the CIDR block allowing access to the current user. There are no restrictions with IP allowlist disabled on the account.\n",
        "responses": {
          "204": {
            "description": "CIDR block successfully deleted.\n"
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "actions-query": {
        "description": "Includes actions you can perform on the object, `false` by default.",
        "in": "query",
        "name": "actions",
        "schema": {
          "default": false,
          "example": true,
          "type": "boolean"
        },
        "x-akamai": {
          "file-path": "parameters/actions-query.yaml"
        }
      },
      "cidr-block-query": {
        "description": "CIDR block or any IP address value you want to validate. Encode any slash characters as `%2F`. This isn't the same as a `cidrBlockId`.",
        "in": "query",
        "name": "cidrblock",
        "required": true,
        "schema": {
          "example": "127.0.0.1/20",
          "type": "string"
        },
        "x-akamai": {
          "file-path": "parameters/cidr-block-query.yaml"
        }
      },
      "cidr-block-id-path": {
        "description": "Unique identifier for each CIDR block. To get this value, run the [List CIDR blocks](ref:get-allowlist) operation.",
        "in": "path",
        "name": "cidrBlockId",
        "required": true,
        "schema": {
          "example": 6688,
          "type": "integer"
        },
        "x-akamai": {
          "file-path": "parameters/cidr-block-id-path.yaml"
        }
      }
    },
    "schemas": {
      "ip-acls-200": {
        "description": "This object encapsulates a collection of CIDR blocks.",
        "items": {
          "additionalProperties": false,
          "properties": {
            "actions": {
              "additionalProperties": false,
              "description": "Specifies activities available for the CIDR block.\n",
              "properties": {
                "delete": {
                  "description": "Whether you can delete this CIDR block. You can't delete a CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                  "type": "boolean"
                },
                "edit": {
                  "description": "Whether you can edit this CIDR block. You can't edit  CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                  "type": "boolean"
                }
              },
              "required": [
                "delete",
                "edit"
              ],
              "type": "object"
            },
            "cidrBlock": {
              "description": "The value of an IP address or IP address range.\n",
              "minLength": 1,
              "type": "string"
            },
            "cidrBlockId": {
              "description": "Unique identifier for each CIDR block.\n",
              "minimum": 0,
              "type": "integer"
            },
            "comments": {
              "description": "Descriptive label you provide for the CIDR block.\n",
              "minLength": 1,
              "type": "string"
            },
            "createdBy": {
              "description": "The user who created the CIDR block.\n",
              "minLength": 1,
              "type": "string"
            },
            "createdDate": {
              "description": "ISO 8601 timestamp indicating when the CIDR block was created.\n",
              "format": "date-time",
              "type": "string"
            },
            "enabled": {
              "description": "Whether the CIDR block is enabled.\n",
              "type": "boolean"
            },
            "modifiedBy": {
              "description": "The user who last edited the CIDR block.\n",
              "minLength": 1,
              "type": "string"
            },
            "modifiedDate": {
              "description": "ISO 8601 timestamp indicating when the CIDR block was last modified.\n",
              "format": "date-time",
              "type": "string"
            }
          },
          "required": [
            "cidrBlock",
            "cidrBlockId",
            "comments",
            "createdBy",
            "createdDate",
            "enabled",
            "modifiedBy",
            "modifiedDate"
          ],
          "type": "object"
        },
        "minItems": 0,
        "type": "array",
        "x-akamai": {
          "file-path": "schemas/ip-acls-200.yaml"
        }
      },
      "post-ip-acl": {
        "additionalProperties": false,
        "description": "Encapsulates all data sent while creating or updating a CIDR block.",
        "properties": {
          "cidrBlock": {
            "description": "The value of an IP address or IP address range.\n",
            "minLength": 1,
            "type": "string"
          },
          "comments": {
            "description": "Descriptive label you provide for the CIDR block.\n",
            "minLength": 1,
            "type": "string"
          },
          "enabled": {
            "description": "Enables the IP allowlist on the account.\n",
            "type": "boolean"
          }
        },
        "required": [
          "enabled",
          "cidrBlock"
        ],
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/post-ip-acl.yaml"
        }
      },
      "ip-acl-200": {
        "additionalProperties": false,
        "description": "Encapsulates all members for a CIDR block in the IP allowlist data structure.",
        "properties": {
          "actions": {
            "additionalProperties": false,
            "description": "Specifies activities available for the CIDR block.\n",
            "properties": {
              "delete": {
                "description": "Whether you can delete this CIDR block. You can't delete a CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                "type": "boolean"
              },
              "edit": {
                "description": "Whether you can edit this CIDR block. You can't edit  CIDR block from an IP address not on the allowlist, or if the CIDR block is the only one on the allowlist.\n",
                "type": "boolean"
              }
            },
            "required": [
              "delete",
              "edit"
            ],
            "type": "object"
          },
          "cidrBlock": {
            "description": "The value of an IP address or IP address range.\n",
            "minLength": 1,
            "type": "string"
          },
          "cidrBlockId": {
            "description": "Unique identifier for each CIDR block.\n",
            "minimum": 0,
            "type": "integer"
          },
          "comments": {
            "description": "Descriptive label you provide for the CIDR block.\n",
            "minLength": 1,
            "type": "string"
          },
          "createdBy": {
            "description": "The user who created the CIDR block.\n",
            "minLength": 1,
            "type": "string"
          },
          "createdDate": {
            "description": "ISO 8601 timestamp indicating when the CIDR block was created.\n",
            "format": "date-time",
            "type": "string"
          },
          "enabled": {
            "description": "Whether the IP allowlist is enabled on the account.\n",
            "type": "boolean"
          },
          "modifiedBy": {
            "description": "The user who last edited the CIDR block.\n",
            "minLength": 1,
            "type": "string"
          },
          "modifiedDate": {
            "description": "ISO 8601 timestamp indicating when the CIDR block was last modified.\n",
            "format": "date-time",
            "type": "string"
          }
        },
        "required": [
          "cidrBlockId",
          "enabled",
          "cidrBlock",
          "createdDate",
          "createdBy",
          "modifiedDate",
          "modifiedBy"
        ],
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/ip-acl-200.yaml"
        }
      },
      "account-status": {
        "additionalProperties": false,
        "description": "Encapsulates the status of IP allowlist on the account.",
        "properties": {
          "enabled": {
            "description": "Whether the IP allowlist is enabled on the account.\n",
            "type": "boolean"
          }
        },
        "required": [
          "enabled"
        ],
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/account-status.yaml"
        }
      }
    },
    "headers": {
      "location": {
        "description": "A URL path to the newly created object.",
        "schema": {
          "type": "string"
        },
        "x-akamai": {
          "file-path": "headers/location.yaml"
        }
      }
    }
  },
  "x-akamai": {
    "auth-type": "EDGE_GRID",
    "file-path": "08-ip-acl.yaml"
  }
}