{
  "openapi": "3.0.0",
  "info": {
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "title": "Groups",
    "version": "2"
  },
  "servers": [
    {
      "url": "https://{hostname}/identity-management/v2"
    }
  ],
  "paths": {
    "/user-admin/groups": {
      "get": {
        "description": "List all groups in which you have a scope of `admin` for the current account and contract type. The account and contract type are determined by the access tokens in your API client.\n",
        "operationId": "get-groups",
        "parameters": [
          {
            "description": "Includes information about actions such as `edit` or `delete` that you can take for the object, `false` by default. Don't confuse this with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
            "in": "query",
            "name": "actions",
            "schema": {
              "default": false,
              "example": true,
              "type": "boolean"
            },
            "x-akamai": {
              "file-path": "parameters/rolesFilterParamsActions_actions.yaml"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": [
                  {
                    "groupId": 12345,
                    "groupName": "Top Level group",
                    "createdDate": "2012-04-28T00:00:00.000Z",
                    "createdBy": "adevi",
                    "modifiedDate": "2012-04-28T00:00:00.000Z",
                    "modifiedBy": "adevi",
                    "actions": {
                      "edit": true,
                      "delete": false
                    },
                    "subGroups": [
                      {
                        "groupId": 12345,
                        "groupName": "First Level SubGroup",
                        "createdDate": "2013-10-29T19:05:52.000Z",
                        "createdBy": "szhang",
                        "modifiedDate": "2017-07-25T22:30:20.000Z",
                        "modifiedBy": "szhang",
                        "parentGroupId": 12345,
                        "actions": {
                          "edit": true,
                          "delete": false
                        },
                        "subGroups": [
                          {
                            "groupId": 54321,
                            "groupName": "Second Level SubGroup",
                            "createdDate": "2017-07-25T22:30:47.000Z",
                            "createdBy": "jdupont",
                            "modifiedDate": "2017-07-25T22:30:47.000Z",
                            "modifiedBy": "alfulani",
                            "parentGroupId": 11111,
                            "subGroups": [],
                            "actions": {
                              "edit": true,
                              "delete": false
                            }
                          }
                        ]
                      }
                    ]
                  }
                ],
                "schema": {
                  "description": "Encapsulates information about a group.\n",
                  "items": {
                    "additionalProperties": false,
                    "description": "Encapsulates information about a group.\n",
                    "properties": {
                      "actions": {
                        "additionalProperties": false,
                        "description": "Encapsulates permissions available to the user for this group. This data is available when you specify the `actions` parameter of the same name, not to be confused with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
                        "properties": {
                          "delete": {
                            "description": "Indicates whether the user can remove items from the group.\n",
                            "type": "boolean"
                          },
                          "edit": {
                            "description": "Indicates whether the user can modify items in the group.\n",
                            "type": "boolean"
                          }
                        },
                        "type": "object"
                      },
                      "createdBy": {
                        "description": "The username of the person who created the group.\n",
                        "type": "string"
                      },
                      "createdDate": {
                        "description": "ISO 8601 timestamp indicating when the group was originally created.\n",
                        "format": "date-time",
                        "type": "string"
                      },
                      "groupId": {
                        "description": "A unique identifier for each group.\n",
                        "type": "integer"
                      },
                      "groupName": {
                        "description": "A group's name.\n",
                        "type": "string"
                      },
                      "modifiedBy": {
                        "description": "The username of the last person to edit the group.\n",
                        "type": "string"
                      },
                      "modifiedDate": {
                        "description": "ISO 8601 timestamp indicating when the group was last updated.\n",
                        "format": "date-time",
                        "type": "string"
                      },
                      "parentGroupId": {
                        "description": "For nested groups, identifies the parent group to which the current group belongs.\n",
                        "type": "integer"
                      },
                      "subGroups": {
                        "description": "Array of nested groups.\n",
                        "items": {
                          "type": "object"
                        },
                        "type": "array"
                      }
                    },
                    "type": "object",
                    "x-akamai": {
                      "file-path": "schemas/GroupResponse.yaml"
                    }
                  },
                  "type": "array",
                  "x-akamai": {
                    "file-path": "schemas/ListOfGroupResponse.yaml"
                  }
                }
              }
            },
            "description": "The response lists groups.\n"
          }
        },
        "summary": "List groups",
        "tags": [
          "Groups"
        ]
      }
    },
    "/user-admin/groups/move": {
      "post": {
        "description": "\"Move a nested group under another group within the same parent hierarchy. Run the [List users affected by moving\na group](ref:get-move-affected-users) operation to check which users would\nbe affected if you were to move a group. \\n\"\n",
        "operationId": "post-groups-move",
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "sourceGroupId": 12345,
                "destinationGroupId": 54321
              },
              "schema": {
                "additionalProperties": false,
                "description": "Describes the request body to move one group under another group.\n",
                "properties": {
                  "destinationGroupId": {
                    "description": "Identifies the group within account hierarchy where you want to move the `sourceGroupId`. It can't be a child or descendant of the current group.\n",
                    "type": "integer"
                  },
                  "sourceGroupId": {
                    "description": "Identifies the nested group you want to move to the `destinationGroupId`.\n",
                    "type": "integer"
                  }
                },
                "required": [
                  "sourceGroupId",
                  "destinationGroupId"
                ],
                "type": "object",
                "x-akamai": {
                  "file-path": "schemas/MoveGroupRequest.yaml"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "Group moved.\n"
          }
        },
        "summary": "Move a group",
        "tags": [
          "Move groups"
        ]
      }
    },
    "/user-admin/groups/move/{sourceGroupId}/{destinationGroupId}/affected-users": {
      "get": {
        "description": "List users who would be affected if you were to move a group. Users may lose or gain access to resources depending on the roles and permissions of the new parent group. Users with a `userType` of `lostAccess` lose their access to the source group. If the `userType` is `gainAccess`, they gain access to the resources in the source group. Users who have inherited access to a group lose access to that group if it moves out of its the hierarchy that gives them those access rights. If the group moves to another parent group to which they have access, they still have access to the group you move. Likewise, when a group is moved to its new location, users who inherit their access rights from the new parent group gain access to the resources in the group you move.\n",
        "operationId": "get-move-affected-users",
        "parameters": [
          {
            "description": "Indicates the type of users to get, either those who have `lostAccess` or the reverse `gainAccess`.\n",
            "in": "query",
            "name": "userType",
            "schema": {
              "enum": [
                "lostAccess",
                "gainAccess"
              ],
              "example": "lostAccess",
              "type": "string"
            },
            "x-akamai": {
              "file-path": "parameters/userType-query.yaml"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": [
                  {
                    "uiIdentityId": "A-B-12345",
                    "firstName": "John",
                    "lastName": "Smith",
                    "accountId": "A-CCT7890",
                    "email": "jsmith@mycompany.com",
                    "uiUserName": "jsmithe@mycompany.com",
                    "lastLoginDate": "2017-08-03T21:15:27.000Z"
                  },
                  {
                    "uiIdentityId": "1-2A3BCD",
                    "firstName": "Jan",
                    "lastName": "Kowalski",
                    "accountId": "A-CCT9012",
                    "email": "jkowalski@barcelona.com",
                    "uiUserName": "jkowalski@barcelona.com",
                    "lastLoginDate": "2016-09-07T00:00:00.000Z"
                  }
                ],
                "schema": {
                  "description": "Lists users affected when moving a group.\n",
                  "items": {
                    "additionalProperties": false,
                    "description": "Specifies the affected user.\n",
                    "properties": {
                      "accountId": {
                        "description": "A unique identifier for each account.\n",
                        "type": "string"
                      },
                      "email": {
                        "description": "The user's email address.\n",
                        "format": "email",
                        "type": "string"
                      },
                      "firstName": {
                        "description": "The user's first name.\n",
                        "type": "string"
                      },
                      "lastLoginDate": {
                        "description": "ISO 8601 timestamp indicating when the user last logged in.\n",
                        "format": "date-time",
                        "type": "string"
                      },
                      "lastName": {
                        "description": "The user's last name.\n",
                        "type": "string"
                      },
                      "uiIdentityId": {
                        "description": "A unique identifier for a user.\n",
                        "type": "string"
                      },
                      "uiUserName": {
                        "description": "The full name for the user, as it appears in interfaces.\n",
                        "type": "string"
                      }
                    },
                    "type": "object"
                  },
                  "type": "array",
                  "x-akamai": {
                    "file-path": "schemas/ListOfMoveUserResponse.yaml"
                  }
                }
              }
            },
            "description": "The response lists affected users.\n"
          }
        },
        "summary": "List users affected by moving a group",
        "tags": [
          "Move groups"
        ]
      },
      "parameters": [
        {
          "description": "The `groupId` for the group you're putting the other group into.\n",
          "in": "path",
          "name": "destinationGroupId",
          "required": true,
          "schema": {
            "example": 32145,
            "type": "integer"
          },
          "x-akamai": {
            "file-path": "parameters/destinationGroupId-path.yaml"
          }
        },
        {
          "description": "The `groupId` for the group you want to move.\n",
          "in": "path",
          "name": "sourceGroupId",
          "required": true,
          "schema": {
            "example": 12345,
            "type": "integer"
          },
          "x-akamai": {
            "file-path": "parameters/sourceGroupId-path.yaml"
          }
        }
      ]
    },
    "/user-admin/groups/{groupId}": {
      "delete": {
        "description": "You can only delete a sub-group, and only if that sub-group doesn't include any users.\n",
        "operationId": "delete-group",
        "responses": {
          "204": {
            "description": "Group deleted.\n"
          }
        },
        "summary": "Delete a group",
        "tags": [
          "Groups"
        ]
      },
      "get": {
        "description": "Return a group's details.\n",
        "operationId": "get-group",
        "parameters": [
          {
            "description": "Includes information about actions such as `edit` or `delete` that you can take for the object, `false` by default. Don't confuse this with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
            "in": "query",
            "name": "actions",
            "schema": {
              "default": false,
              "example": true,
              "type": "boolean"
            },
            "x-akamai": {
              "file-path": "parameters/rolesFilterParamsActions_actions.yaml"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "groupId": 12345,
                  "groupName": "TopLevelGroup",
                  "createdDate": "2012-04-28T00:00:00.000Z",
                  "createdBy": "mrossi",
                  "modifiedDate": "2012-04-28T00:00:00.000Z",
                  "modifiedBy": "hgildong",
                  "actions": {
                    "edit": true,
                    "delete": false
                  },
                  "subGroups": [
                    {
                      "groupId": 32145,
                      "groupName": "First Level SubGroup",
                      "createdDate": "2013-10-29T19:05:52.000Z",
                      "createdBy": "mrossi",
                      "modifiedDate": "2017-07-25T22:30:20.000Z",
                      "modifiedBy": "hgildong",
                      "parentGroupId": 12345,
                      "actions": {
                        "edit": true,
                        "delete": false
                      },
                      "subGroups": [
                        {
                          "groupId": 54321,
                          "groupName": "Second Level SubGroup",
                          "createdDate": "2017-07-25T22:30:47.000Z",
                          "createdBy": "jperez",
                          "modifiedDate": "2017-07-25T22:30:47.000Z",
                          "modifiedBy": "mrossi",
                          "parentGroupId": 11111,
                          "subGroups": [],
                          "actions": {
                            "edit": true,
                            "delete": false
                          }
                        }
                      ]
                    }
                  ]
                },
                "schema": {
                  "additionalProperties": false,
                  "description": "Encapsulates information about a group.\n",
                  "properties": {
                    "actions": {
                      "additionalProperties": false,
                      "description": "Encapsulates permissions available to the user for this group. This data is available when you specify the `actions` parameter of the same name, not to be confused with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
                      "properties": {
                        "delete": {
                          "description": "Indicates whether the user can remove items from the group.\n",
                          "type": "boolean"
                        },
                        "edit": {
                          "description": "Indicates whether the user can modify items in the group.\n",
                          "type": "boolean"
                        }
                      },
                      "type": "object"
                    },
                    "createdBy": {
                      "description": "The username of the person who created the group.\n",
                      "type": "string"
                    },
                    "createdDate": {
                      "description": "ISO 8601 timestamp indicating when the group was originally created.\n",
                      "format": "date-time",
                      "type": "string"
                    },
                    "groupId": {
                      "description": "A unique identifier for each group.\n",
                      "type": "integer"
                    },
                    "groupName": {
                      "description": "A group's name.\n",
                      "type": "string"
                    },
                    "modifiedBy": {
                      "description": "The username of the last person to edit the group.\n",
                      "type": "string"
                    },
                    "modifiedDate": {
                      "description": "ISO 8601 timestamp indicating when the group was last updated.\n",
                      "format": "date-time",
                      "type": "string"
                    },
                    "parentGroupId": {
                      "description": "For nested groups, identifies the parent group to which the current group belongs.\n",
                      "type": "integer"
                    },
                    "subGroups": {
                      "description": "Array of nested groups.\n",
                      "items": {
                        "type": "object"
                      },
                      "type": "array"
                    }
                  },
                  "type": "object",
                  "x-akamai": {
                    "file-path": "schemas/GroupResponse.yaml"
                  }
                }
              }
            },
            "description": "The response returns the group.\n"
          }
        },
        "summary": "Get a group",
        "tags": [
          "Groups"
        ]
      },
      "parameters": [
        {
          "description": "A unique identifier for each group.\n",
          "in": "path",
          "name": "groupId",
          "required": true,
          "schema": {
            "example": 54321,
            "type": "integer"
          },
          "x-akamai": {
            "file-path": "parameters/groupId-path.yaml"
          }
        }
      ],
      "post": {
        "description": "Create a new group within a parent group you specify in the request.\n",
        "operationId": "post-group",
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "groupName": "New Sub Group"
              },
              "schema": {
                "additionalProperties": false,
                "description": "Specifies the name for a group.\n",
                "properties": {
                  "groupName": {
                    "description": "A group's name.\n",
                    "maxLength": 50,
                    "minLength": 1,
                    "type": "string"
                  }
                },
                "required": [
                  "groupName"
                ],
                "type": "object",
                "x-akamai": {
                  "file-path": "schemas/GroupRequest.yaml"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "groupId": 32145,
                  "groupName": "New Sub Group",
                  "parentGroupId": 19807,
                  "createdDate": "2017-09-18T19:03:28.000Z",
                  "createdBy": "jperez",
                  "modifiedDate": "2017-09-18T19:03:28.000Z",
                  "modifiedBy": "alfulani"
                },
                "schema": {
                  "additionalProperties": false,
                  "description": "Encapsulates information about a group.\n",
                  "properties": {
                    "actions": {
                      "additionalProperties": false,
                      "description": "Encapsulates permissions available to the user for this group. This data is available when you specify the `actions` parameter of the same name, not to be confused with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
                      "properties": {
                        "delete": {
                          "description": "Indicates whether the user can remove items from the group.\n",
                          "type": "boolean"
                        },
                        "edit": {
                          "description": "Indicates whether the user can modify items in the group.\n",
                          "type": "boolean"
                        }
                      },
                      "type": "object"
                    },
                    "createdBy": {
                      "description": "The username of the person who created the group.\n",
                      "type": "string"
                    },
                    "createdDate": {
                      "description": "ISO 8601 timestamp indicating when the group was originally created.\n",
                      "format": "date-time",
                      "type": "string"
                    },
                    "groupId": {
                      "description": "A unique identifier for each group.\n",
                      "type": "integer"
                    },
                    "groupName": {
                      "description": "A group's name.\n",
                      "type": "string"
                    },
                    "modifiedBy": {
                      "description": "The username of the last person to edit the group.\n",
                      "type": "string"
                    },
                    "modifiedDate": {
                      "description": "ISO 8601 timestamp indicating when the group was last updated.\n",
                      "format": "date-time",
                      "type": "string"
                    },
                    "parentGroupId": {
                      "description": "For nested groups, identifies the parent group to which the current group belongs.\n",
                      "type": "integer"
                    },
                    "subGroups": {
                      "description": "Array of nested groups.\n",
                      "items": {
                        "type": "object"
                      },
                      "type": "array"
                    }
                  },
                  "type": "object",
                  "x-akamai": {
                    "file-path": "schemas/GroupResponse.yaml"
                  }
                }
              }
            },
            "description": "The response returns the created group.\n"
          }
        },
        "summary": "Create a new group",
        "tags": [
          "Groups"
        ]
      },
      "put": {
        "description": "Change the name of the group.\n",
        "operationId": "put-group",
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "groupName": "Change Group Name"
              },
              "schema": {
                "additionalProperties": false,
                "description": "Specifies the name for a group.\n",
                "properties": {
                  "groupName": {
                    "description": "A group's name.\n",
                    "maxLength": 50,
                    "minLength": 1,
                    "type": "string"
                  }
                },
                "required": [
                  "groupName"
                ],
                "type": "object",
                "x-akamai": {
                  "file-path": "schemas/GroupRequest.yaml"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "example": {
                  "groupId": 12345,
                  "groupName": "Change Group Name",
                  "createdDate": "2012-04-28T00:00:00.000Z",
                  "createdBy": "adevi",
                  "modifiedDate": "2012-04-28T00:00:00.000Z",
                  "modifiedBy": "alfulani",
                  "actions": {
                    "edit": true,
                    "delete": false
                  },
                  "subGroups": [
                    {
                      "groupId": 12345,
                      "groupName": "First Level SubGroup",
                      "createdDate": "2013-10-29T19:05:52.000Z",
                      "createdBy": "jkowalski",
                      "modifiedDate": "2017-07-25T22:30:20.000Z",
                      "modifiedBy": "jkowalski",
                      "parentGroupId": 12345,
                      "actions": {
                        "edit": true,
                        "delete": false
                      },
                      "subGroups": [
                        {
                          "groupId": 12345,
                          "groupName": "Second Level SubGroup",
                          "createdDate": "2017-07-25T22:30:47.000Z",
                          "createdBy": "adevi",
                          "modifiedDate": "2017-07-25T22:30:47.000Z",
                          "modifiedBy": "szhang",
                          "parentGroupId": 11111,
                          "subGroups": [],
                          "actions": {
                            "edit": true,
                            "delete": false
                          }
                        }
                      ]
                    }
                  ]
                },
                "schema": {
                  "additionalProperties": false,
                  "description": "Encapsulates information about a group.\n",
                  "properties": {
                    "actions": {
                      "additionalProperties": false,
                      "description": "Encapsulates permissions available to the user for this group. This data is available when you specify the `actions` parameter of the same name, not to be confused with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
                      "properties": {
                        "delete": {
                          "description": "Indicates whether the user can remove items from the group.\n",
                          "type": "boolean"
                        },
                        "edit": {
                          "description": "Indicates whether the user can modify items in the group.\n",
                          "type": "boolean"
                        }
                      },
                      "type": "object"
                    },
                    "createdBy": {
                      "description": "The username of the person who created the group.\n",
                      "type": "string"
                    },
                    "createdDate": {
                      "description": "ISO 8601 timestamp indicating when the group was originally created.\n",
                      "format": "date-time",
                      "type": "string"
                    },
                    "groupId": {
                      "description": "A unique identifier for each group.\n",
                      "type": "integer"
                    },
                    "groupName": {
                      "description": "A group's name.\n",
                      "type": "string"
                    },
                    "modifiedBy": {
                      "description": "The username of the last person to edit the group.\n",
                      "type": "string"
                    },
                    "modifiedDate": {
                      "description": "ISO 8601 timestamp indicating when the group was last updated.\n",
                      "format": "date-time",
                      "type": "string"
                    },
                    "parentGroupId": {
                      "description": "For nested groups, identifies the parent group to which the current group belongs.\n",
                      "type": "integer"
                    },
                    "subGroups": {
                      "description": "Array of nested groups.\n",
                      "items": {
                        "type": "object"
                      },
                      "type": "array"
                    }
                  },
                  "type": "object",
                  "x-akamai": {
                    "file-path": "schemas/GroupResponse.yaml"
                  }
                }
              }
            },
            "description": "The response returns the modified group.\n"
          }
        },
        "summary": "Modify a group's name",
        "tags": [
          "Groups"
        ]
      }
    }
  },
  "components": {
    "parameters": {
      "rolesFilterParamsActions_actions": {
        "description": "Includes information about actions such as `edit` or `delete` that you can take for the object, `false` by default. Don't confuse this with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
        "in": "query",
        "name": "actions",
        "schema": {
          "default": false,
          "example": true,
          "type": "boolean"
        },
        "x-akamai": {
          "file-path": "parameters/rolesFilterParamsActions_actions.yaml"
        }
      },
      "destinationGroupId-path": {
        "description": "The `groupId` for the group you're putting the other group into.\n",
        "in": "path",
        "name": "destinationGroupId",
        "required": true,
        "schema": {
          "example": 32145,
          "type": "integer"
        },
        "x-akamai": {
          "file-path": "parameters/destinationGroupId-path.yaml"
        }
      },
      "sourceGroupId-path": {
        "description": "The `groupId` for the group you want to move.\n",
        "in": "path",
        "name": "sourceGroupId",
        "required": true,
        "schema": {
          "example": 12345,
          "type": "integer"
        },
        "x-akamai": {
          "file-path": "parameters/sourceGroupId-path.yaml"
        }
      },
      "userType-query": {
        "description": "Indicates the type of users to get, either those who have `lostAccess` or the reverse `gainAccess`.\n",
        "in": "query",
        "name": "userType",
        "schema": {
          "enum": [
            "lostAccess",
            "gainAccess"
          ],
          "example": "lostAccess",
          "type": "string"
        },
        "x-akamai": {
          "file-path": "parameters/userType-query.yaml"
        }
      },
      "groupId-path": {
        "description": "A unique identifier for each group.\n",
        "in": "path",
        "name": "groupId",
        "required": true,
        "schema": {
          "example": 54321,
          "type": "integer"
        },
        "x-akamai": {
          "file-path": "parameters/groupId-path.yaml"
        }
      }
    },
    "schemas": {
      "GroupResponse": {
        "additionalProperties": false,
        "description": "Encapsulates information about a group.\n",
        "properties": {
          "actions": {
            "additionalProperties": false,
            "description": "Encapsulates permissions available to the user for this group. This data is available when you specify the `actions` parameter of the same name, not to be confused with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
            "properties": {
              "delete": {
                "description": "Indicates whether the user can remove items from the group.\n",
                "type": "boolean"
              },
              "edit": {
                "description": "Indicates whether the user can modify items in the group.\n",
                "type": "boolean"
              }
            },
            "type": "object"
          },
          "createdBy": {
            "description": "The username of the person who created the group.\n",
            "type": "string"
          },
          "createdDate": {
            "description": "ISO 8601 timestamp indicating when the group was originally created.\n",
            "format": "date-time",
            "type": "string"
          },
          "groupId": {
            "description": "A unique identifier for each group.\n",
            "type": "integer"
          },
          "groupName": {
            "description": "A group's name.\n",
            "type": "string"
          },
          "modifiedBy": {
            "description": "The username of the last person to edit the group.\n",
            "type": "string"
          },
          "modifiedDate": {
            "description": "ISO 8601 timestamp indicating when the group was last updated.\n",
            "format": "date-time",
            "type": "string"
          },
          "parentGroupId": {
            "description": "For nested groups, identifies the parent group to which the current group belongs.\n",
            "type": "integer"
          },
          "subGroups": {
            "description": "Array of nested groups.\n",
            "items": {
              "type": "object"
            },
            "type": "array"
          }
        },
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/GroupResponse.yaml"
        }
      },
      "ListOfGroupResponse": {
        "description": "Encapsulates information about a group.\n",
        "items": {
          "additionalProperties": false,
          "description": "Encapsulates information about a group.\n",
          "properties": {
            "actions": {
              "additionalProperties": false,
              "description": "Encapsulates permissions available to the user for this group. This data is available when you specify the `actions` parameter of the same name, not to be confused with the `action` parameter, which applies to the [Set two-factor authentication](ref:put-user-profile-tfa) operation.\n",
              "properties": {
                "delete": {
                  "description": "Indicates whether the user can remove items from the group.\n",
                  "type": "boolean"
                },
                "edit": {
                  "description": "Indicates whether the user can modify items in the group.\n",
                  "type": "boolean"
                }
              },
              "type": "object"
            },
            "createdBy": {
              "description": "The username of the person who created the group.\n",
              "type": "string"
            },
            "createdDate": {
              "description": "ISO 8601 timestamp indicating when the group was originally created.\n",
              "format": "date-time",
              "type": "string"
            },
            "groupId": {
              "description": "A unique identifier for each group.\n",
              "type": "integer"
            },
            "groupName": {
              "description": "A group's name.\n",
              "type": "string"
            },
            "modifiedBy": {
              "description": "The username of the last person to edit the group.\n",
              "type": "string"
            },
            "modifiedDate": {
              "description": "ISO 8601 timestamp indicating when the group was last updated.\n",
              "format": "date-time",
              "type": "string"
            },
            "parentGroupId": {
              "description": "For nested groups, identifies the parent group to which the current group belongs.\n",
              "type": "integer"
            },
            "subGroups": {
              "description": "Array of nested groups.\n",
              "items": {
                "type": "object"
              },
              "type": "array"
            }
          },
          "type": "object",
          "x-akamai": {
            "file-path": "schemas/GroupResponse.yaml"
          }
        },
        "type": "array",
        "x-akamai": {
          "file-path": "schemas/ListOfGroupResponse.yaml"
        }
      },
      "MoveGroupRequest": {
        "additionalProperties": false,
        "description": "Describes the request body to move one group under another group.\n",
        "properties": {
          "destinationGroupId": {
            "description": "Identifies the group within account hierarchy where you want to move the `sourceGroupId`. It can't be a child or descendant of the current group.\n",
            "type": "integer"
          },
          "sourceGroupId": {
            "description": "Identifies the nested group you want to move to the `destinationGroupId`.\n",
            "type": "integer"
          }
        },
        "required": [
          "sourceGroupId",
          "destinationGroupId"
        ],
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/MoveGroupRequest.yaml"
        }
      },
      "ListOfMoveUserResponse": {
        "description": "Lists users affected when moving a group.\n",
        "items": {
          "additionalProperties": false,
          "description": "Specifies the affected user.\n",
          "properties": {
            "accountId": {
              "description": "A unique identifier for each account.\n",
              "type": "string"
            },
            "email": {
              "description": "The user's email address.\n",
              "format": "email",
              "type": "string"
            },
            "firstName": {
              "description": "The user's first name.\n",
              "type": "string"
            },
            "lastLoginDate": {
              "description": "ISO 8601 timestamp indicating when the user last logged in.\n",
              "format": "date-time",
              "type": "string"
            },
            "lastName": {
              "description": "The user's last name.\n",
              "type": "string"
            },
            "uiIdentityId": {
              "description": "A unique identifier for a user.\n",
              "type": "string"
            },
            "uiUserName": {
              "description": "The full name for the user, as it appears in interfaces.\n",
              "type": "string"
            }
          },
          "type": "object"
        },
        "type": "array",
        "x-akamai": {
          "file-path": "schemas/ListOfMoveUserResponse.yaml"
        }
      },
      "GroupRequest": {
        "additionalProperties": false,
        "description": "Specifies the name for a group.\n",
        "properties": {
          "groupName": {
            "description": "A group's name.\n",
            "maxLength": 50,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "groupName"
        ],
        "type": "object",
        "x-akamai": {
          "file-path": "schemas/GroupRequest.yaml"
        }
      }
    }
  },
  "x-akamai": {
    "auth-type": "EDGE_GRID",
    "file-path": "groups-api.yaml"
  }
}